import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'en' | 'zh' | 'ru' | 'kk';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    'nav.home': 'Home',
    'nav.courses': 'Courses',
    'nav.vocabulary': 'Vocabulary',
    'nav.homework': 'Homework',
    'nav.classroom': 'Live Class',
    'nav.students': 'Students',
    'nav.reports': 'Reports',
    'nav.login': 'Login',
    'nav.register': 'Free Registration',
    'app.logo.title': 'LingoBridge',
    'app.logo.subtitle': 'Chinese for Global Citizens',
    'nav.methodology': 'Methodology',
    'nav.teachers': 'Teachers',
    'hero.title': 'Learn Chinese Starting from Here',
    'hero.subtitle': 'Specialized Chinese course for Russian speakers with immersion and thoughtful design.',
    'hero.student_btn': "I'm a Student",
    'hero.teacher_btn': "I'm a Teacher",
    'hero.login_prompt': 'Already have an account?',
    'dashboard.welcome': 'Welcome back',
    'dashboard.quote': '"Learning is a habit... Keep pushing your boundaries and master Mandarin one character at a time."',
    'dashboard.continue': 'Continue Learning',
    'dashboard.schedule': 'View Schedule',
    'dashboard.streak': 'Current Streak',
    'dashboard.points': 'Total Points',
    'dashboard.tasks': "Today's Tasks",
    'dashboard.view_all': 'View All Tasks',
    'footer.desc': 'Bridge the cultural gap and master the language of the future with LingoBridge\'s award-winning curriculum.',
    'footer.education': 'Education',
    'footer.support': 'Support',
    'footer.legal': 'Legal',
    'footer.courses_syllabus': 'Courses & Syllabus',
    'footer.teachers': 'Teacher Portals',
    'footer.mobile': 'Mobile App',
    'footer.help': 'Help Center',
    'footer.contact': 'Contact Us',
    'footer.docs': 'Documentation',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    'partners.title': 'Global Academic Partners',
    'steps.title': 'Your Path to Fluency',
    'steps.subtitle': 'Achievement in 3 simple steps',
    'stats.learners': 'Active Learners',
    'stats.partners': 'Partner Schools',
    'feature.step1.title': '1. Pre-learning',
    'feature.step1.desc': 'Vocabulary cards, meaning explanations, and stroke animations.',
    'feature.step2.title': '2. Online Classes',
    'feature.step2.desc': 'Live classes with teachers, interactive communication, no boredom.',
    'feature.step3.title': '3. Practice & Points',
    'feature.step3.desc': 'Pronunciation analysis, rankings, game tasks - progress with every step.',
    'showcase.recording.title': 'Speech Recognition',
    'showcase.recording.desc': 'Record and analyze your pronunciation in real-time with AI-powered feedback.',
    'showcase.meeting.title': 'Live Meeting Room',
    'showcase.meeting.desc': 'Interactive classroom experience with real-time translation and whiteboards.',
    'showcase.multi_device.title': 'Multi-platform Sync',
    'showcase.multi_device.desc': 'Seamlessly switch between Mac, iPad, and iPhone while keeping your progress.',
    'classroom.recording': 'Recording',
    'classroom.upload_pdf': 'Upload PDF',
    'classroom.clear_canvas': 'Clear Ink',
    'classroom.start_screen_hint': 'Start sharing your screen to begin Local Mode.',
    'schedule.replays': 'History & Replays',
    'schedule.view_replay': 'Watch Replay',
    'classroom.participants': 'Participants',
    'classroom.chat': 'Chat',
    'classroom.poll': 'Live Poll',
    'classroom.translate': 'Translate',
    'classroom.settings': 'Settings',
    'classroom.mute': 'Mute Mic',
    'classroom.camera': 'Toggle Camera',
    'classroom.screen': 'Share Screen',
    'classroom.stop_share': 'Stop Share',
    'classroom.leave': 'Leave Class',
    'classroom.topic': 'Daily Topic',
    'classroom.subtitles': 'Real-time Subtitles',
    'classroom.bilingual': 'ZH / EN',
    'classroom.students': 'Students',
    'classroom.active': 'Active',
    'vocab.message_placeholder': 'Message classroom...',
    'vocab.poll_question': "What is the correct Pinyin for '大家好'?",
    'vocab.study_modes': 'Study Modes',
    'vocab.search_placeholder': 'Search words...',
    'vocab.launch_game': 'Launch Game',
    'vocab.start_review': 'Start Review',
    'classroom.course_title': 'Basic Chinese (Part 1)',
    'dashboard.greeting_teacher': 'Bonjour, Instructor Li!',
    'dashboard.greeting_student': 'Hello, Anna Zhang!',
    'dashboard.overview': 'Here is what\'s happening with your classes today.',
    'dashboard.view_all_action': 'View All',
    'dashboard.schedule_label': 'Daily Schedule',
    'homework.title': 'Speaking Practice',
    'homework.active_task': 'Active Task',
    'homework.subtitle': 'Please read the following sentence clearly into your microphone.',
    'homework.due': 'Due',
    'homework.pages': 'Pages',
    'homework.tip': 'Tip: Focused on tone consistency and flow.',
    'homework.recording': 'RECORDING...',
    'homework.ready': 'Ready to Practice',
    'homework.latest': 'Latest Recordings (Max 3)',
    'homework.score': 'Score',
    'homework.ai_eval': 'AI Evaluation',
    'homework.total_score': 'SCORE',
    'homework.excellent': 'Excellent!',
    'homework.great': 'Great Job!',
    'homework.keep_practicing': 'Keep Practicing!',
    'homework.eval_desc': 'Your fluency is superb. Focus on specific character pronunciations.',
    'homework.fluency': 'Fluency',
    'homework.tone': 'Tone Accuracy',
    'homework.pronunciation': 'Pronunciation',
    'homework.completeness': 'Completeness',
    'homework.grammar': 'Grammar & Correction',
    'homework.tone_deviation': 'Tone Deviation',
    'homework.tone_desc': 'Small deviation detected. Try to emphasize the tone.',
    'homework.learning_tip': 'Learning Tip',
    'homework.learning_desc': 'Record once more focusing on breathing.',
    'homework.model_answer': 'Model Answer',
    'homework.prev': 'Previous Question',
    'homework.explain': 'Explain',
    'homework.greetings_basics': 'Greetings & Basics',
    'homework.family_jobs': 'Family & Jobs',
    'homework.daily_routine': 'Daily Routine',
    'homework.shopping': 'Shopping',
    'homework.more_coming': 'More Lessons Coming Soon',
    'homework.back_path': 'Back to Path',
    'homework.progress': 'Progress',
    'homework.lesson_greet': 'Basic Greetings',
    'homework.lesson_intro': 'Self Introduction',
    'homework.lesson_family': 'Family Members',
    'homework.lesson_mom': 'Describing My Mom',
    'homework.lesson_family_para': 'Short Paragraph: My Family',
    'homework.lesson_time': 'Time & Actions',
    'homework.lesson_schedule': 'My Schedule',
    'homework.save': 'Save Progress',
    'homework.next': 'Next Task',
    'homework.path_title': 'My Learning Path',
    'homework.path_desc': 'Complete assignments to synchronize with your classroom curriculum.',
    'homework.unit': 'Unit',
    'homework.lesson': 'Lesson',
    'homework.start_task': 'Start Assignment',
    'homework.type.speaking': 'Speaking Practice',
    'homework.type.vocab': 'Vocabulary Drill',
    'homework.type.reading': 'Reading Comprehension',
    'homework.completed': 'Completed',
    'homework.locked': 'Locked',
    'homework.stats.title': 'Learning Stats',
    'homework.stats.mistakes': 'Mistakes',
    'homework.stats.favorites': 'Favorites',
    'homework.stats.records': 'History',
    'homework.stats.graph': 'Knowledge Graph',
    'homework.stats.syllabus': 'Course Syllabus',
    'homework.stats.mindmap': 'Mind Map',
    'homework.stats.ranking': 'Global Rankings',
    'homework.stats.streak': 'Day Streak',
    'homework.stats.points': 'Exp Points',
    'vocab.study_now': 'Study Now',
    'vocab.review': 'Review',
    'vocab.mastery': 'Mastery',
    'vocab.learning_title': 'Learning Session',
    'vocab.correct': 'Correct!',
    'vocab.incorrect': 'Incorrect',
    'vocab.check': 'Check Answer',
    'vocab.continue': 'Continue',
    'vocab.finish': 'Finish Session',
    'vocab.translate_to_ru': 'Translate to Russian',
    'vocab.translate_to_zh': 'Translate to Chinese',
    'vocab.pronounce': 'Pronounce the word',
    'vocab.phonetic_group': 'Phonetic Group Study',
    'schedule.sync': 'Sync Google Calendar',
    'schedule.syncing': 'Syncing...',
    'schedule.synced': 'Synced with Google Calendar',
    'schedule.deadlines': 'Deadlines',
    'schedule.upcoming': 'Upcoming Live Sessions',
    'schedule.agenda': 'Agenda',
    'schedule.week': 'Week',
    'schedule.join_class': 'Join Live Class',
    'schedule.details': 'Details',
    'schedule.add_personal': 'Add Personal Schedule',
    'schedule.tomorrow': 'Tomorrow',
    'schedule.month_year': 'April 2026',
    'schedule.days_short': 'S M T W T F S',
    'schedule.live_badge': 'Live',
    'schedule.instr': 'Instructor',
    'notification.title': 'Notifications',
    'notification.mark_all': 'Mark all as read',
    'notification.view_all': 'View all notifications',
    'course.basic': 'Basic Chinese (Part 1)',
    'course.vocab': 'HSK 3 Vocabulary Review',
    'course.culture': 'Chinese Culture & History',
    'course.quiz': 'Vocabulary Quiz',
    'stats.days': 'days',
    'stats.pts': 'pts',
    'stats.starting_in': 'Starting in',
    'stats.minutes': 'minutes',
    'dashboard.join_classroom': 'Join Classroom',
    'dashboard.task.preview': 'Preview Assignment',
    'dashboard.task.prep_family': 'Preparation: Lesson 3 "Family"',
    'dashboard.task.prep_desc': 'Study new vocabulary and grammar patterns for the upcoming lesson.',
    'dashboard.task.start': 'Start Assignment',
    'dashboard.task.live_soon': 'Live Soon',
    'dashboard.task.reminder': 'Class Reminder',
    'dashboard.task.live_lesson': '14:00 Online Lesson: HSK 3 Grammar',
    'dashboard.task.homework': 'Homework',
    'dashboard.task.review_ch2': 'Review: Chapter 2 Comprehension',
    'dashboard.task.review_desc': 'Complete the listening and reading exercises from previous unit.',
    'dashboard.task.submit': 'Submit Task',
    'dashboard.quick_access': 'Quick Access',
    'dashboard.my_schedule': 'My Schedule',
    'dashboard.week_stats': 'Week Stats',
    'dashboard.char_lab': 'Character Lab',
    'dashboard.live_events': 'Live Events',
    'dashboard.ranking': 'Weekly Ranking',
    'dashboard.leaderboard': 'Full Leaderboard',
    'showcase.optimized_desc': 'Seamless learning experiences optimized for every device in your life.',
    'showcase.lesson_label': 'Lesson 1',
    'showcase.now_live': 'Now Live',
    'showcase.lesson_title': 'Evening HSK Intensive',
    'showcase.cloud_presence': 'Cloud Presence: Active',
    'showcase.ai_core': 'AI Core',
    'showcase.low_latency': 'Low Latency',
    'showcase.multi_lang': 'Multi-Language',
    'showcase.phonetic': 'mā ma',
    'showcase.meaning': 'Mother',
    'showcase.example_zh': 'Zhè shì wǒ māma.',
    'showcase.example_en': '"This is my mother."',
    'footer.rights': '© 2024 LingoBridge Learning Systems. All Rights Reserved.',
    'vocab.repo_desc': 'Your personalized repository of Chinese terms.',
    'vocab.spaced_active': 'Spaced Repetition Active',
    'vocab.mastered': 'Mastered',
    'vocab.learning': 'Learning',
    'vocab.new': 'New',
    'vocab.rhyme': 'Rhyme',
    'vocab.cluster': 'Word Cluster',
    'vocab.launch': 'Launch',
    'vocab.add_word': 'Add Word',
    'vocab.recommended': 'Recommended for you',
    'vocab.master_title': 'Master 15 New Words with Spaced Repetition',
    'vocab.ai_analyze': 'Our AI analyzed your recent mistakes. Today\'s review focus:',
    'vocab.start_ai': 'Start AI Review',
    'vocab.next_review': 'Next Review: Tomorrow',
    'vocab.weekly_rank': 'Weekly Rank: #12',
    'vocab.session_complete': 'Session Complete!',
    'vocab.session_desc': 'You mastered {score} questions in this session.',
    'vocab.accuracy': 'Accuracy',
    'vocab.exp_gained': 'Exp Gained',
    'vocab.hold_speak': 'Hold to Speak',
    'vocab.pron_great': 'Great pronunciation!',
    'vocab.pron_well': 'Well done! Moving to next.',
    'vocab.pron_low': 'Score is below the 80 threshold. Try again!',
    'vocab.correct_is': 'Correct is:',
    'course.my_courses': 'My Courses',
    'course.manage': 'Manage your learning materials and active classrooms.',
    'course.create': 'Create New Course',
    'course.title_placeholder': 'Course title',
    'course.upload': 'Upload',
    'course.upload_hint': 'Select a course, then upload .pptx/.pdf for pages or .xlsx for practice exercises.',
    'course.upload_result': '{filename} uploaded. Pages: {pages}, exercises: {exercises}.',
    'course.loading': 'Loading courses...',
    'course.load_failed': 'Failed to load courses. Start backend on port 3001.',
    'course.created': 'Course created.',
    'course.create_failed': 'Create course failed.',
    'course.upload_failed': 'Upload failed.',
    'course.untitled': 'New Chinese Course',
    'course.no_description': 'No description yet.',
    'course.exercises': 'Exercises',
    'course.upload_courseware': 'Upload Courseware',
    'course.upload_excel': 'Upload Excel',
    'course.excel_result': '{filename} uploaded. Tasks: {tasks}, vocabulary: {vocab}.',
    'course.excel_warnings': 'Warnings',
    'course.published': 'Published',
    'course.draft': 'Draft',
    'course.edit': 'Edit Content',
    'course.enter': 'Enter Class',
    'course.reports': 'Learning Reports',
    'course.add_new': 'Add New Course',
    'course.custom_syllabus': 'Create custom syllabus and curriculum',
    'course.spring': 'Spring Semester 2024',
    'course.autumn': 'Autumn Semester 2023',
    'course.summer': 'Summer 2024',
    'course.advanced': 'Advanced Mandarin (HSK 4 Prep)',
    'course.business': 'Business Chinese for Professionals',
    'course.hsk1_unit4': 'Beginner HSK 1 - Unit 4',
    'course.business_prep': 'Business Chinese Prep',
    'course.workshop': 'Interactive Workshop',
    'course.level1': 'Level 1',
    'course.level4': 'Level 4',
    'course.mixed': 'Mixed Level',
    'classroom.end_confirm_title': 'End Class for Everyone?',
    'classroom.end_confirm_desc': 'This will close the classroom for all students. Are you sure?',
    'classroom.end_btn': 'End Class',
    'classroom.cancel': 'Cancel',
    'classroom.end_poll': 'End Poll',
    'classroom.interactive_assessment': 'Interactive Assessment',
    'classroom.ppt_locked': 'PPT Locked for Students',
    'classroom.ppt_unlocked': 'Students Can Browse PPT',
    'classroom.key_vocab': "Today's Key Vocabulary",
    'classroom.transcript_title': 'Real-time AI Transcript & Translation Record',
    'classroom.cn_ru_active': 'CN-RU Pipeline Active',
    'classroom.system_ready': 'System Ready • Analyzing Speech...',
    'classroom.mic_studio': 'STUDIO MIC',
    'classroom.mic_off': 'MIC OFF',
    'classroom.screen_sharing': 'Screen Sharing Active',
    'classroom.presentation_locked': 'Presentation Locked',
    'classroom.live_discussion': 'Live Discussion',
    'classroom.waiting_interaction': 'Waiting for student interaction...',
    'classroom.say_something': 'Say something to everyone...',
    'classroom.leave_confirm_title': 'Leave Classroom?',
    'classroom.leave_confirm_desc': 'Are you sure you want to end your learning session?',
    'classroom.live_stream': 'Live Stream',
    'classroom.you_on_stage': 'YOU • On Stage',
    'classroom.rec': 'REC',
    'classroom.ai_trans_log': 'AI Real-time Translation Log',
    'classroom.listening_translating': 'Listening for speech and translating...',
    'classroom.start_conversation': 'Start a conversation. Your message will also appear as a bullet comment!',
    'classroom.hand_raise_required': 'Hand raise required',
    'classroom.mute_mic': 'Mute Mic',
    'classroom.unmute_mic': 'Unmute Mic',
    'classroom.stop_video': 'Stop Video',
    'classroom.start_video': 'Start Video',
    'classroom.raise_hand': 'Raise Hand',
    'classroom.waiting_teacher': 'Waiting for Teacher...',
    'classroom.on_stage': 'On Stage',
    'classroom.stop_recording': 'Stop Recording',
    'classroom.record_lesson': 'Record Lesson',
    'classroom.exit_fullscreen': 'Exit Fullscreen',
    'login.subtitle': 'Continue your Chinese mastery journey',
    'login.email_label': 'Email Address',
    'login.password_label': 'Password',
    'login.forgot_password': 'Forgot password?',
    'login.continue_with': 'or continue with',
    'login.no_account': "Don't have an account?",
    'register.subtitle': 'Start your journey to global communication',
    'register.full_name': 'Full Name',
    'register.student': 'Student',
    'register.teacher': 'Teacher',
    'register.terms': 'I agree to the Terms of Service and Privacy Policy.',
    'register.get_started': 'Get Started',
    'register.already_account': 'Already have an account?',
    'reports.title': 'Performance Analytics',
    'reports.subtitle': 'Deep dive into student engagement and curriculum efficacy.',
    'reports.export': 'Export CSV',
    'reports.engagement_rate': 'Class Engagement Rate',
    'reports.proficiency_level': 'Average Proficiency Level',
    'reports.certificates': 'Certificates Issued',
    'reports.active_time': 'Active Learning Time',
    'reports.accuracy': 'Assessment Accuracy',
    'reports.last_7_days': 'Last 7 Days',
    'reports.last_30_days': 'Last 30 Days',
    'reports.daily_avg': 'Daily Avg',
    'reports.efficacy_title': 'Efficacy by Course',
    'reports.filter_courses': 'Filter courses...',
    'reports.table_module': 'Course Module',
    'reports.table_score': 'Avg. Score',
    'reports.table_completion': 'Completion Rate',
    'reports.table_trend': 'Trend',
    'reports.stable': 'Stable',
    'reports.at_risk': 'At Risk',
    'students.title': 'Active Students',
    'students.subtitle': 'Monitor progress and engagement across your classes.',
    'students.search_placeholder': 'Search students...',
    'students.table_student': 'Student',
    'students.table_engagement': 'Engagement',
    'students.table_attendance': 'Attendance',
    'students.table_status': 'Status',
    'students.table_actions': 'Actions',
    'students.active_label': 'Active',
    'students.on_track': 'On Track',
    'students.at_risk': 'At Risk',
    'students.excellence': 'Excellence',
    'students.total_students': 'Total Students',
    'students.avg_attendance': 'Avg. Attendance',
    'students.students_at_risk': 'Students at Risk',
    'time.ago': 'ago',
    'time.hours': 'hours',
    'time.minutes': 'minutes',
    'time.days': 'days',
    'time.now': 'Now',
    'homework.pass': 'PASS',
    'homework.fail': 'FAIL',
    'homework.today': 'Today',
    'homework.no_assignments': 'No assignments for this lesson yet.',
    'teacher.weekly_engagement': 'Weekly Engagement',
    'teacher.quiz_completion': 'Quiz Completion',
    'teacher.student_satisfaction': 'Student Satisfaction',
    'teacher.action_needed': 'Action Needed',
    'teacher.homework_reminder': '12 students have not submitted their Unit 3 homework yet.',
    'teacher.remind_all': 'REMIND ALL',
    'teacher.recent_activity': 'Recent Activity',
    'teacher.activity_submitted': 'submitted',
    'teacher.activity_enrolled': 'enrolled in',
    'teacher.activity_messaged': 'sent a message regarding',
    'teacher.view_audit': 'VIEW FULL AUDIT',
  },
  zh: {
    'nav.home': '首页',
    'nav.courses': '课程',
    'nav.vocabulary': '词汇',
    'nav.homework': '作业',
    'nav.classroom': '直播课',
    'nav.students': '学生',
    'nav.reports': '报告',
    'nav.login': '登录',
    'nav.register': '免费注册',
    'app.logo.title': 'LingoBridge',
    'app.logo.subtitle': '全球公民的中文桥梁',
    'nav.methodology': '教学法',
    'nav.teachers': '名师阵容',
    'hero.title': '从这里开始学习中文',
    'hero.subtitle': '专为俄语使用者设计的沉浸式中文课程，精心设计的学习体验。',
    'hero.student_btn': '我是学生，想学习',
    'hero.teacher_btn': '我是老师',
    'hero.login_prompt': '已有账号？',
    'dashboard.welcome': '欢迎回来',
    'dashboard.quote': '“学习是一种习惯... 不断挑战自我，逐字攻克中文。”',
    'dashboard.continue': '继续学习',
    'dashboard.schedule': '查看日程',
    'dashboard.streak': '当前连续',
    'dashboard.points': '总积分',
    'dashboard.tasks': '今日任务',
    'dashboard.view_all': '查看全部任务',
    'footer.desc': '通过 LingoBridge 屡获殊荣的课程，弥合文化鸿沟，掌握未来的语言。',
    'footer.education': '教育',
    'footer.support': '支持',
    'footer.legal': '法律信息',
    'footer.courses_syllabus': '课程与大纲',
    'footer.teachers': '教师门户',
    'footer.mobile': '移动应用',
    'footer.help': '帮助中心',
    'footer.contact': '联系我们',
    'footer.docs': '文档',
    'footer.privacy': '隐私政策',
    'footer.terms': '服务条款',
    'partners.title': '全球学术合作伙伴',
    'steps.title': '您的流利之路',
    'steps.subtitle': '简单三步，实现跨越',
    'stats.learners': '活跃学员',
    'stats.partners': '合作院校',
    'feature.step1.title': '1. 预习阶段',
    'feature.step1.desc': '词汇卡片、释义说明和汉字书写动画。',
    'feature.step2.title': '2. 在线课程',
    'feature.step2.desc': '与老师进行直播授课，互动沟通，拒绝枯燥。',
    'feature.step3.title': '3. 练习与积分',
    'feature.step3.desc': '发音分析、排名、游戏化任务——每一步都在进步。',
    'showcase.recording.title': '语音识别录音',
    'showcase.recording.desc': '通过AI反馈实时记录并分析您的发音。',
    'showcase.meeting.title': '实时会议系统',
    'showcase.meeting.desc': '配备实时翻译和白板的互动课室体验。',
    'showcase.multi_device.title': '多端同步',
    'showcase.multi_device.desc': '在 Mac、iPad 和 iPhone 之间无缝切换，保持学习进度。',
    'classroom.recording': '录制中',
    'classroom.upload_pdf': '上传 PDF',
    'classroom.clear_canvas': '清除笔迹',
    'classroom.start_screen_hint': '开始共享屏幕以进入本地模式。',
    'schedule.replays': '历史与回看',
    'schedule.view_replay': '查看回看',
    'classroom.participants': '参会者',
    'classroom.chat': '聊天',
    'classroom.poll': '实时投票',
    'classroom.translate': '翻译',
    'classroom.settings': '设置',
    'classroom.mute': '静音麦克风',
    'classroom.camera': '切换摄像头',
    'classroom.screen': '共享屏幕',
    'classroom.stop_share': '停止共享',
    'classroom.leave': '离开课堂',
    'classroom.topic': '今日主题',
    'classroom.subtitles': '实时字幕',
    'classroom.bilingual': '中 / 英',
    'classroom.students': '学生',
    'classroom.active': '活跃',
    'classroom.message_placeholder': '发送消息...',
    'classroom.poll_question': "“大家好”的正确拼音是什么？",
    'vocab.study_modes': '学习模式',
    'vocab.search_placeholder': '搜索单词...',
    'vocab.launch_game': '开始游戏',
    'vocab.start_review': '开始复习',
    'classroom.course_title': '基础汉语 (第一部分)',
    'dashboard.greeting_teacher': '你好，李老师！',
    'dashboard.greeting_student': '你好，安娜！',
    'dashboard.overview': '这是您今天的教学概况。',
    'dashboard.view_all_action': '查看全部',
    'dashboard.schedule_label': '今日日程',
    'homework.title': '口语练习',
    'homework.active_task': '进行中任务',
    'homework.subtitle': '请对着麦克风清晰地读出以下句子。',
    'homework.due': '截止时间',
    'homework.pages': '页',
    'homework.tip': '提示：专注于声调的准确性和语流。',
    'homework.recording': '录音中...',
    'homework.ready': '准备好练习了吗',
    'homework.latest': '最近录音（最多3条）',
    'homework.score': '得分',
    'homework.ai_eval': 'AI 评估',
    'homework.total_score': '分数',
    'homework.excellent': '太棒了！',
    'homework.great': '做得好！',
    'homework.keep_practicing': '继续努力！',
    'homework.eval_desc': '你的流利度非常好。请多关注具体汉字的发音。',
    'homework.fluency': '流利度',
    'homework.tone': '声调准确度',
    'homework.pronunciation': '发音',
    'homework.completeness': '完整度',
    'homework.grammar': '语法与纠错',
    'homework.tone_deviation': '声调偏差',
    'homework.tone_desc': '检测到较小偏差。尝试加强该声调。',
    'homework.learning_tip': '学习提示',
    'homework.learning_desc': '再录一次，注意短句之间的呼吸。',
    'homework.model_answer': '标准答案',
    'homework.prev': '上一题',
    'homework.explain': '详解',
    'homework.greetings_basics': '问候与基础',
    'homework.family_jobs': '家庭与工作',
    'homework.daily_routine': '日常生活',
    'homework.shopping': '购物',
    'homework.more_coming': '更多课程即将推出',
    'homework.back_path': '返回路径',
    'homework.progress': '进度',
    'homework.lesson_greet': '基础问候',
    'homework.lesson_intro': '自我介绍',
    'homework.lesson_family': '家庭成员',
    'homework.lesson_mom': '描写我的妈妈',
    'homework.lesson_family_para': '短文：我的家庭',
    'homework.lesson_time': '时间与动作',
    'homework.lesson_schedule': '我的日程',
    'homework.save': '保存进度',
    'homework.next': '下一题',
    'homework.path_title': '我的学习路径',
    'homework.path_desc': '完成与课堂教材同步的课后作业。',
    'homework.unit': '单元',
    'homework.lesson': '课程',
    'homework.start_task': '开始作业',
    'homework.type.speaking': '口语练习',
    'homework.type.vocab': '单词巩固',
    'homework.type.reading': '阅读理解',
    'homework.completed': '已完成',
    'homework.locked': '未解锁',
    'homework.stats.title': '学习统计',
    'homework.stats.mistakes': '错题本',
    'homework.stats.favorites': '收藏本',
    'homework.stats.records': '学习记录',
    'homework.stats.graph': '知识图谱',
    'homework.stats.syllabus': '课程大纲',
    'homework.stats.mindmap': '思维导图',
    'homework.stats.ranking': '各校排名',
    'homework.stats.streak': '连续学习',
    'homework.stats.points': '经验值',
    'vocab.study_now': '立即学习',
    'vocab.review': '复习',
    'vocab.mastery': '掌握度',
    'vocab.learning_title': '学习环节',
    'vocab.correct': '正确！',
    'vocab.incorrect': '不正确',
    'vocab.check': '检查',
    'vocab.continue': '继续',
    'vocab.finish': '结束环节',
    'vocab.translate_to_ru': '翻译成俄语',
    'vocab.translate_to_zh': '翻译成中文',
    'vocab.pronounce': '读出这个单词',
    'vocab.phonetic_group': '音韵分组学习',
    'schedule.sync': '同步谷歌日历',
    'schedule.syncing': '同步中...',
    'schedule.synced': '已同步谷歌日历',
    'schedule.deadlines': '截止日期',
    'schedule.upcoming': '即将开始的直播课',
    'schedule.agenda': '议程',
    'schedule.week': '周',
    'schedule.join_class': '加入直播课',
    'schedule.details': '详情',
    'schedule.add_personal': '添加个人日程',
    'schedule.tomorrow': '明天',
    'schedule.month_year': '2026年4月',
    'schedule.days_short': '日 一 二 三 四 五 六',
    'schedule.live_badge': '直播中',
    'schedule.instr': '讲师',
    'notification.title': '通知',
    'notification.mark_all': '全部标记为已读',
    'notification.view_all': '查看全部通知',
    'course.basic': '基础汉语 (第一部分)',
    'course.vocab': 'HSK 3 词汇复习',
    'course.culture': '中国文化与历史',
    'course.quiz': '词汇测试',
    'stats.days': '天',
    'stats.pts': '积分',
    'stats.starting_in': '还有',
    'stats.minutes': '分钟开始',
    'dashboard.join_classroom': '进入课堂',
    'dashboard.task.preview': '预习任务',
    'dashboard.task.prep_family': '预习：第三课“家庭”',
    'dashboard.task.prep_desc': '学习下节课的新词汇和语法结构。',
    'dashboard.task.start': '开始任务',
    'dashboard.task.live_soon': '即将开始',
    'dashboard.task.reminder': '上课提醒',
    'dashboard.task.live_lesson': '14:00 在线课程：HSK 3 语法',
    'dashboard.task.homework': '课后作业',
    'dashboard.task.review_ch2': '复习：第二章理解',
    'dashboard.task.review_desc': '完成上一个单元的听力和阅读练习。',
    'dashboard.task.submit': '提交任务',
    'dashboard.quick_access': '快速访问',
    'dashboard.my_schedule': '我的日程',
    'dashboard.week_stats': '周统计',
    'dashboard.char_lab': '汉字实验室',
    'dashboard.live_events': '直播活动',
    'dashboard.ranking': '周排名',
    'dashboard.leaderboard': '完整排行榜',
    'showcase.optimized_desc': '为您的各种设备优化的无缝学习体验。',
    'showcase.lesson_label': '第1课',
    'showcase.now_live': '正在直播',
    'showcase.lesson_title': '晚间 HSK 强化课程',
    'showcase.cloud_presence': '云端同步：已激活',
    'showcase.ai_core': 'AI 核心',
    'showcase.low_latency': '低延迟',
    'showcase.multi_lang': '多语言',
    'showcase.phonetic': 'mā ma',
    'showcase.meaning': '妈妈',
    'showcase.example_zh': '这是我妈妈。',
    'showcase.example_en': '"这是我妈妈。"',
    'footer.rights': '© 2024 LingoBridge 学习系统。保留所有权利。',
    'vocab.repo_desc': '您的个性化中文词库。',
    'vocab.spaced_active': '间隔复习已激活',
    'vocab.mastered': '已掌握',
    'vocab.learning': '学习中',
    'vocab.new': '新词',
    'vocab.rhyme': '韵脚',
    'vocab.cluster': '词簇',
    'vocab.launch': '启动',
    'vocab.add_word': '添加单词',
    'vocab.recommended': '为你推荐',
    'vocab.master_title': '通过间隔复习掌握15个新词',
    'vocab.ai_analyze': '我们的AI分析了你最近的错误。今天的复习重点：',
    'vocab.start_ai': '开始AI复习',
    'vocab.next_review': '下次复习：明天',
    'vocab.weekly_rank': '周排名：第12名',
    'vocab.session_complete': '练习完成！',
    'vocab.session_desc': '你在本次练习中掌握了 {score} 个问题。',
    'vocab.accuracy': '准确率',
    'vocab.exp_gained': '获得经验',
    'vocab.hold_speak': '按住说话',
    'vocab.pron_great': '发音很棒！',
    'vocab.pron_well': '做得好！进入下一题。',
    'vocab.pron_low': '分数低于80分。再试一次！',
    'vocab.correct_is': '正确答案是：',
    'course.my_courses': '我的课程',
    'course.manage': '管理教学材料、作业文件和活跃课堂。',
    'course.create': '创建新课程',
    'course.title_placeholder': '课程标题',
    'course.upload': '上传',
    'course.upload_hint': '选择课程后，上传 .pptx/.pdf 生成课件页，或上传 .xlsx 生成练习作业。',
    'course.upload_result': '{filename} 已上传。课件页：{pages}，练习：{exercises}。',
    'course.loading': '正在加载课程...',
    'course.load_failed': '课程加载失败，请确认 3001 端口后端已启动。',
    'course.created': '课程已创建。',
    'course.create_failed': '课程创建失败。',
    'course.upload_failed': '上传失败。',
    'course.untitled': '新中文课程',
    'course.no_description': '暂无课程说明。',
    'course.exercises': '练习',
    'course.upload_courseware': '上传课件',
    'course.upload_excel': '上传 Excel',
    'course.excel_result': '{filename} 已上传。作业：{tasks}，词汇：{vocab}。',
    'course.excel_warnings': '警告',
    'course.published': '已发布',
    'course.draft': '草稿',
    'course.edit': '编辑内容',
    'course.enter': '进入课堂',
    'course.reports': '学习报告',
    'course.add_new': '添加新课程',
    'course.custom_syllabus': '创建自定义大纲和课程',
    'course.spring': '2024年春季学期',
    'course.autumn': '2023年秋季学期',
    'course.summer': '2024年夏季',
    'course.advanced': '高级汉语 (HSK 4 备考)',
    'course.business': '商务汉语',
    'course.hsk1_unit4': '初级汉语 HSK 1 - 第4单元',
    'course.business_prep': '商务汉语备考',
    'course.workshop': '互动研讨会',
    'course.level1': '1级',
    'course.level4': '4级',
    'course.mixed': '混合级别',
    'classroom.end_confirm_title': '为所有人结束课程？',
    'classroom.end_confirm_desc': '这将关闭所有学生的教室。您确定吗？',
    'classroom.end_btn': '结束课程',
    'classroom.cancel': '取消',
    'classroom.end_poll': '结束投票',
    'classroom.interactive_assessment': '互动评测',
    'classroom.ppt_locked': '学生端 PPT 已锁定',
    'classroom.ppt_unlocked': '学生可自由浏览 PPT',
    'classroom.key_vocab': '今日核心词汇',
    'classroom.transcript_title': '实时 AI 转录与翻译记录',
    'classroom.cn_ru_active': '中俄翻译链路已激活',
    'classroom.system_ready': '系统就绪 • 正在分析语音...',
    'classroom.mic_studio': '工作室麦克风',
    'classroom.mic_off': '麦克风关闭',
    'classroom.screen_sharing': '屏幕共享中',
    'classroom.presentation_locked': '演示已锁定',
    'classroom.live_discussion': '实时讨论',
    'classroom.waiting_interaction': '等待学生互动...',
    'classroom.say_something': '向大家说点什么...',
    'classroom.leave_confirm_title': '离开教室？',
    'classroom.leave_confirm_desc': '您确定要结束学习课程吗？',
    'classroom.live_stream': '直播流',
    'classroom.you_on_stage': '您 • 正在连麦',
    'classroom.rec': '录制',
    'classroom.ai_trans_log': 'AI 实时翻译日志',
    'classroom.listening_translating': '正在倾听语音并翻译...',
    'classroom.start_conversation': '开始对话。您的消息也将以弹幕形式出现！',
    'classroom.hand_raise_required': '需要举手申请',
    'classroom.mute_mic': '静音麦克风',
    'classroom.unmute_mic': '取消静音',
    'classroom.stop_video': '停止视频',
    'classroom.start_video': '开启视频',
    'classroom.raise_hand': '举手',
    'classroom.waiting_teacher': '等待老师...',
    'classroom.on_stage': '连麦中',
    'classroom.stop_recording': '停止录制',
    'classroom.record_lesson': '录制课程',
    'classroom.exit_fullscreen': '退出全屏',
    'login.subtitle': '继续您的中文精进之旅',
    'login.email_label': '电子邮箱',
    'login.password_label': '密码',
    'login.forgot_password': '忘记密码？',
    'login.continue_with': '或使用以下方式继续',
    'login.no_account': '还没有账号？',
    'register.subtitle': '开启您的全球沟通之旅',
    'register.full_name': '全名',
    'register.student': '学生',
    'register.teacher': '老师',
    'register.terms': '我同意服务条款和隐私政策。',
    'register.get_started': '立即开始',
    'register.already_account': '已有账号？',
    'reports.title': '教学表现分析',
    'reports.subtitle': '深入分析学生参与度和课程效果。',
    'reports.export': '导出 CSV',
    'reports.engagement_rate': '课堂参与率',
    'reports.proficiency_level': '平均熟练度',
    'reports.certificates': '已发放证书',
    'reports.active_time': '活跃学习时间',
    'reports.accuracy': '评估准确率',
    'reports.last_7_days': '最近7天',
    'reports.last_30_days': '最近30天',
    'reports.daily_avg': '每日平均',
    'reports.efficacy_title': '各课程效果',
    'reports.filter_courses': '过滤课程...',
    'reports.table_module': '课程模块',
    'reports.table_score': '平均分',
    'reports.table_completion': '完成率',
    'reports.table_trend': '趋势',
    'reports.stable': '稳定',
    'reports.at_risk': '有风险',
    'students.title': '活跃学生',
    'students.subtitle': '监控班级进度和参与度。',
    'students.search_placeholder': '搜索学生...',
    'students.table_student': '学生',
    'students.table_engagement': '参与度',
    'students.table_attendance': '出勤率',
    'students.table_status': '状态',
    'students.table_actions': '操作',
    'students.active_label': '活跃',
    'students.on_track': '正常进度',
    'students.at_risk': '有风险',
    'students.excellence': '优秀',
    'students.total_students': '学生总数',
    'students.avg_attendance': '平均出勤率',
    'students.students_at_risk': '有风险的学生',
    'time.ago': '前',
    'time.hours': '小时',
    'time.minutes': '分钟',
    'time.days': '天',
    'time.now': '现在',
    'homework.pass': '通过',
    'homework.fail': '不通过',
    'homework.today': '今天',
    'homework.no_assignments': '该练习暂未发布作业。',
    'teacher.weekly_engagement': '每周参与度',
    'teacher.quiz_completion': '测验完成率',
    'teacher.student_satisfaction': '学生满意度',
    'teacher.action_needed': '待办事项',
    'teacher.homework_reminder': '还有12名学生未提交第三单元作业。',
    'teacher.remind_all': '一键催交',
    'teacher.recent_activity': '近期动态',
    'teacher.activity_submitted': '提交了',
    'teacher.activity_enrolled': '报名了',
    'teacher.activity_messaged': '留言关于',
    'teacher.view_audit': '查看完整日志',
  },
  ru: {
    'nav.home': 'Главная',
    'nav.courses': 'Курсы',
    'nav.vocabulary': 'Словарь',
    'nav.homework': 'Домашнее задание',
    'nav.classroom': 'Онлайн-урок',
    'nav.students': 'Студенты',
    'nav.reports': 'Отчеты',
    'nav.login': 'Войти',
    'nav.register': 'Бесплатная регистрация',
    'app.logo.title': 'LingoBridge',
    'app.logo.subtitle': 'Китайский для граждан мира',
    'nav.methodology': 'Методология',
    'nav.teachers': 'Преподаватели',
    'hero.title': 'Изучайте китайский начиная отсюда',
    'hero.subtitle': 'Специальный курс китайского языка для русскоговорящих с погружением и продуманным дизайном.',
    'hero.student_btn': 'Я студент, хочу учиться',
    'hero.teacher_btn': 'Я преподаватель',
    'hero.login_prompt': 'Уже есть аккаунт?',
    'dashboard.welcome': 'С возвращением',
    'dashboard.quote': '«Обучение - это привычка... Продолжайте расширять свои границы и осваивать китайский язык по одному иероглифу за раз».',
    'dashboard.continue': 'Продолжить обучение',
    'dashboard.schedule': 'Посмотреть расписание',
    'dashboard.streak': 'Текущая серия',
    'dashboard.points': 'Всего баллов',
    'dashboard.tasks': 'Задачи на сегодня',
    'dashboard.view_all': 'Все задачи',
    'footer.desc': 'Преодолевайте культурный разрыв и осваивайте язык будущего с отмеченной наградами учебной программой LingoBridge.',
    'footer.education': 'Продукт',
    'footer.support': 'Поддержка',
    'footer.legal': 'Правовая информация',
    'footer.courses_syllabus': 'Курсы и программа',
    'footer.teachers': 'Портал для учителей',
    'footer.mobile': 'Мобильное приложение',
    'footer.help': 'Справочный центр',
    'footer.contact': 'Связаться с нами',
    'footer.docs': 'Документация',
    'footer.privacy': 'Политика конфиденциальности',
    'footer.terms': 'Условия использования',
    'partners.title': 'Глобальные академические партнеры',
    'steps.title': 'Ваш путь к беглости',
    'steps.subtitle': 'Достижение цели за 3 простых шага',
    'stats.learners': 'Активные студенты',
    'stats.partners': 'Партнерские школы',
    'feature.step1.title': '1. Предварительное изучение',
    'feature.step1.desc': 'Словарные карточки, объяснения значений и анимация написания иероглифов.',
    'feature.step2.title': '2. Онлайн-уроки',
    'feature.step2.desc': 'Живые уроки с преподавателем, интерактивное общение, никакой скуки.',
    'feature.step3.title': '3. Практика и баллы',
    'feature.step3.desc': 'Анализ произношения, рейтинги, игровые задания — прогресс с каждым шагом.',
    'showcase.recording.title': 'Распознавание речи',
    'showcase.recording.desc': 'Записывайте и анализируйте свое произношение в реальном времени с помощью ИИ.',
    'showcase.meeting.title': 'Онлайн-конференции',
    'showcase.meeting.desc': 'Интерактивное обучение в реальном времени с переводом и белыми досками.',
    'showcase.multi_device.title': 'Синхронизация устройств',
    'showcase.multi_device.desc': 'Переключайтесь между Mac, iPad и iPhone, сохраняя прогресс в обучении.',
    'classroom.recording': 'Запись',
    'classroom.upload_pdf': 'Загрузить PDF',
    'classroom.clear_canvas': 'Очистить чернила',
    'classroom.start_screen_hint': 'Начните демонстрацию экрана для локального режима.',
    'schedule.replays': 'История и записи',
    'schedule.view_replay': 'Смотреть запись',
    'classroom.participants': 'Участники',
    'classroom.chat': 'Чат',
    'classroom.poll': 'Опрос',
    'classroom.translate': 'Перевод',
    'classroom.settings': 'Настройки',
    'classroom.mute': 'Выключить звук',
    'classroom.camera': 'Включить камеру',
    'classroom.screen': 'Демонстрация экрана',
    'classroom.stop_share': 'Остановить показ',
    'classroom.leave': 'Выйти из класса',
    'classroom.topic': 'Тема дня',
    'classroom.subtitles': 'Субтитры в реальном времени',
    'classroom.bilingual': 'КИТ / АНГЛ',
    'classroom.students': 'Студенты',
    'classroom.active': 'Активно',
    'classroom.message_placeholder': 'Написать сообщение...',
    'classroom.poll_question': "Какой правильный пиньинь для '大家好'?",
    'vocab.study_modes': 'Режимы обучения',
    'vocab.search_placeholder': 'Поиск слов...',
    'vocab.launch_game': 'Запустить игру',
    'vocab.start_review': 'Начать повторение',
    'dashboard.greeting_teacher': 'Здравствуйте, Ли Лаоши!',
    'dashboard.greeting_student': 'Привет, Анна!',
    'dashboard.overview': 'Вот обзор вашего расписания на сегодня.',
    'dashboard.view_all_action': 'Смотреть все',
    'dashboard.schedule_label': 'Задачи на сегодня',
    'homework.title': 'Разговорная практика',
    'homework.active_task': 'Активное задание',
    'homework.subtitle': 'Пожалуйста, четко прочитайте следующее предложение в микрофон.',
    'homework.due': 'Срок',
    'homework.pages': 'Страницы',
    'homework.tip': 'Совет: сосредоточьтесь на последовательности тонов и плавности.',
    'homework.recording': 'ЗАПИСЬ...',
    'homework.ready': 'Готовы к практике',
    'homework.latest': 'Последние записи (макс. 3)',
    'homework.score': 'Баллы',
    'homework.ai_eval': 'Оценка ИИ',
    'homework.total_score': 'БАЛЛЫ',
    'homework.excellent': 'Отлично!',
    'homework.great': 'Отличная работа!',
    'homework.keep_practicing': 'Продолжайте практиковаться!',
    'homework.eval_desc': 'У вас отличная беглость. Сосредоточьтесь на произношении конкретных иероглифов.',
    'homework.fluency': 'Беглость',
    'homework.tone': 'Точность тонов',
    'homework.pronunciation': 'Произношение',
    'homework.completeness': 'Полнота',
    'homework.grammar': 'Грамматика и исправления',
    'homework.tone_deviation': 'Отклонение тона',
    'homework.tone_desc': 'Обнаружено небольшое отклонение. Попробуйте подчеркнуть тон.',
    'homework.learning_tip': 'Совет по обучению',
    'homework.learning_desc': 'Запишите еще раз, сосредоточившись на дыхании.',
    'homework.model_answer': 'Вариант ответа',
    'homework.prev': 'Предыдущий вопрос',
    'homework.explain': 'Объяснить',
    'homework.greetings_basics': 'Приветствия и основы',
    'homework.family_jobs': 'Семья и работа',
    'homework.daily_routine': 'Распорядок дня',
    'homework.shopping': 'Покупки',
    'homework.more_coming': 'Больше уроков скоро',
    'homework.back_path': 'Назад к пути',
    'homework.progress': 'Прогресс',
    'homework.lesson_greet': 'Базовые приветствия',
    'homework.lesson_intro': 'О себе',
    'homework.lesson_family': 'Члены семьи',
    'homework.lesson_mom': 'Описание мамы',
    'homework.lesson_family_para': 'Короткий абзац: Моя семья',
    'homework.lesson_time': 'Время и действия',
    'homework.lesson_schedule': 'Мой график',
    'homework.save': 'Сохранить прогресс',
    'homework.next': 'Следующее задание',
    'homework.path_title': 'Мой путь обучения',
    'homework.path_desc': 'Выполняйте задания, соответствующие вашей школьной программе.',
    'homework.unit': 'Модуль',
    'homework.lesson': 'Урок',
    'homework.start_task': 'Начать задание',
    'homework.type.speaking': 'Разговорная практика',
    'homework.type.vocab': 'Упражнения на слова',
    'homework.type.reading': 'Понимание прочитанного',
    'homework.completed': 'Завершено',
    'homework.locked': 'Заблокировано',
    'homework.stats.title': 'Статистика',
    'homework.stats.mistakes': 'Ошибки',
    'homework.stats.favorites': 'Избранное',
    'homework.stats.records': 'История',
    'homework.stats.graph': 'Граф знаний',
    'homework.stats.syllabus': 'Учебный план',
    'homework.stats.mindmap': 'Интеллект-карта',
    'homework.stats.ranking': 'Рейтинги',
    'homework.stats.streak': 'Ударный режим',
    'homework.stats.points': 'Очки опыта',
    'vocab.study_now': 'Учить сейчас',
    'vocab.review': 'Повторить',
    'vocab.mastery': 'Освоение',
    'vocab.learning_title': 'Сессия обучения',
    'vocab.correct': 'Правильно!',
    'vocab.incorrect': 'Неправильно',
    'vocab.check': 'Проверить',
    'vocab.continue': 'Продолжить',
    'vocab.finish': 'Завершить сессию',
    'vocab.translate_to_ru': 'Перевести на русский',
    'vocab.translate_to_zh': 'Перевести на китайский',
    'vocab.pronounce': 'Произнесите слово',
    'vocab.phonetic_group': 'Фонетическая группа',
    'schedule.sync': 'Синхронизировать Google Календарь',
    'schedule.syncing': 'Синхронизация...',
    'schedule.synced': 'Синхронизировано с Google Календарем',
    'schedule.deadlines': 'Дедлайны',
    'schedule.upcoming': 'Предстоящие сессии',
    'schedule.agenda': 'Повестка',
    'schedule.week': 'Неделя',
    'schedule.join_class': 'Присоединиться к уроку',
    'schedule.details': 'Подробнее',
    'schedule.add_personal': 'Добавить личное расписание',
    'schedule.tomorrow': 'Завтра',
    'schedule.month_year': 'Апрель 2026',
    'schedule.days_short': 'В П В С Ч П С',
    'schedule.live_badge': 'В эфире',
    'schedule.instr': 'Инструктор',
    'notification.title': 'Уведомления',
    'notification.mark_all': 'Отметить все как прочитанные',
    'notification.view_all': 'Посмотреть все уведомления',
    'course.basic': 'Китайский для начинающих (Ч. 1)',
    'course.vocab': 'Повторение слов HSK 3',
    'course.culture': 'Китайская культура и история',
    'course.quiz': 'Тест по словам',
    'stats.days': 'дн.',
    'stats.pts': 'очков',
    'stats.starting_in': 'Начинается через',
    'stats.minutes': 'мин.',
    'dashboard.join_classroom': 'Войти в класс',
    'dashboard.task.preview': 'Предварительное задание',
    'dashboard.task.prep_family': 'Подготовка: Урок 3 «Семья»',
    'dashboard.task.prep_desc': 'Изучите новую лексику и грамматические структуры к следующему уроку.',
    'dashboard.task.start': 'Начать задание',
    'dashboard.task.live_soon': 'Скоро в эфире',
    'dashboard.task.reminder': 'Напоминание о занятии',
    'dashboard.task.live_lesson': '14:00 Онлайн-урок: Грамматика HSK 3',
    'dashboard.task.homework': 'Домашнее задание',
    'dashboard.task.review_ch2': 'Повторение: Понимание главы 2',
    'dashboard.task.review_desc': 'Выполните упражнения на аудирование и чтение из предыдущего модуля.',
    'dashboard.task.submit': 'Сдать работу',
    'dashboard.quick_access': 'Быстрый доступ',
    'dashboard.my_schedule': 'Мое расписание',
    'dashboard.week_stats': 'Статистика недели',
    'dashboard.char_lab': 'Лаборатория иероглифов',
    'dashboard.live_events': 'Живые события',
    'dashboard.ranking': 'Рейтинг недели',
    'dashboard.leaderboard': 'Полная таблица',
    'showcase.optimized_desc': 'Бесшовный процесс обучения, оптимизированный для любого устройства в вашей жизни.',
    'showcase.lesson_label': 'Урок 1',
    'showcase.now_live': 'В прямом эфире',
    'showcase.lesson_title': 'Вечерний интенсив HSK',
    'showcase.cloud_presence': 'Облачная синхронизация: Активна',
    'showcase.ai_core': 'ИИ Ядро',
    'showcase.low_latency': 'Низкая задержка',
    'showcase.multi_lang': 'Многоязычность',
    'showcase.phonetic': 'mā ma',
    'showcase.meaning': 'Мама',
    'showcase.example_zh': 'Zhè shì wǒ māma.',
    'showcase.example_en': '"Это моя мама."',
    'footer.rights': '© 2024 LingoBridge Learning Systems. Все права защищены.',
    'vocab.repo_desc': 'Ваш персональный репозиторий китайских терминов.',
    'vocab.spaced_active': 'Интервальное повторение активно',
    'vocab.mastered': 'Освоено',
    'vocab.learning': 'Изучается',
    'vocab.new': 'Новое',
    'vocab.rhyme': 'Рифма',
    'vocab.cluster': 'Группа слов',
    'vocab.launch': 'Запуск',
    'vocab.add_word': 'Добавить слово',
    'vocab.recommended': 'Рекомендовано для вас',
    'vocab.master_title': 'Освойте 15 новых слов с интервальным повторением',
    'vocab.ai_analyze': 'Наш ИИ проанализировал ваши недавние ошибки. Сегодня в фокусе:',
    'vocab.start_ai': 'Начать ИИ-повторение',
    'vocab.next_review': 'Следующее повторение: Завтра',
    'vocab.weekly_rank': 'Место в рейтинге: #12',
    'vocab.session_complete': 'Сессия завершена!',
    'vocab.session_desc': 'Вы освоили {score} вопросов в этой сессии.',
    'vocab.accuracy': 'Точность',
    'vocab.exp_gained': 'Опыт получен',
    'vocab.hold_speak': 'Удерживайте, чтобы говорить',
    'vocab.pron_great': 'Отличное произношение!',
    'vocab.pron_well': 'Хорошо! Переходим к следующему.',
    'vocab.pron_low': 'Балл ниже порога 80. Попробуйте еще раз!',
    'vocab.correct_is': 'Правильно:',
    'course.my_courses': 'Мои курсы',
    'course.manage': 'Управляйте учебными материалами и активными классами.',
    'course.create': 'Создать новый курс',
    'course.title_placeholder': 'Название курса',
    'course.upload': 'Загрузить',
    'course.upload_hint': 'Выберите курс, затем загрузите .pptx/.pdf для страниц или .xlsx для упражнений.',
    'course.upload_result': '{filename} загружен. Страниц: {pages}, упражнений: {exercises}.',
    'course.loading': 'Загрузка курсов...',
    'course.load_failed': 'Не удалось загрузить курсы. Запустите backend на порту 3001.',
    'course.created': 'Курс создан.',
    'course.create_failed': 'Не удалось создать курс.',
    'course.upload_failed': 'Загрузка не удалась.',
    'course.untitled': 'Новый курс китайского',
    'course.no_description': 'Описание пока не добавлено.',
    'course.exercises': 'Упражнения',
    'course.upload_courseware': 'Загрузить материалы',
    'course.upload_excel': 'Загрузить Excel',
    'course.excel_result': '{filename} загружен. Заданий: {tasks}, слова: {vocab}.',
    'course.excel_warnings': 'Предупреждения',
    'course.published': 'Опубликовано',
    'course.draft': 'Черновик',
    'course.edit': 'Изменить контент',
    'course.enter': 'Войти в класс',
    'course.reports': 'Отчеты об обучении',
    'course.add_new': 'Добавить курс',
    'course.custom_syllabus': 'Создать учебный план и программу',
    'course.spring': 'Весенний семестр 2024',
    'course.autumn': 'Осенний семестр 2023',
    'course.summer': 'Лето 2024',
    'course.advanced': 'Продвинутый китайский (Подготовка к HSK 4)',
    'course.business': 'Деловой китайский для профессионалов',
    'course.hsk1_unit4': 'Китайский для начинающих HSK 1 - Блок 4',
    'course.business_prep': 'Подготовка к деловому китайскому',
    'course.workshop': 'Интерактивный воркшоп',
    'course.level1': 'Уровень 1',
    'course.level4': 'Уровень 4',
    'course.mixed': 'Смешанный уровень',
    'classroom.end_confirm_title': 'Завершить урок для всех?',
    'classroom.end_confirm_desc': 'Это закроет класс для всех учеников. Вы уверены?',
    'classroom.end_btn': 'Завершить урок',
    'classroom.cancel': 'Отмена',
    'classroom.end_poll': 'Завершить опрос',
    'classroom.interactive_assessment': 'Интерактивная оценка',
    'classroom.ppt_locked': 'PPT заблокирован для студентов',
    'classroom.ppt_unlocked': 'Студенты могут просматривать PPT',
    'classroom.key_vocab': 'Ключевая лексика дня',
    'classroom.transcript_title': 'Запись ИИ-транскрипции и перевода в реальном времени',
    'classroom.cn_ru_active': 'Канал CN-RU активен',
    'classroom.system_ready': 'Система готова • Анализ речи...',
    'classroom.mic_studio': 'СТУДИЙНЫЙ МИК',
    'classroom.mic_off': 'МИК ВЫКЛ',
    'classroom.screen_sharing': 'Демонстрация экрана активна',
    'classroom.presentation_locked': 'Презентация заблокирована',
    'classroom.live_discussion': 'Живая дискуссия',
    'classroom.waiting_interaction': 'Ожидание взаимодействия со студентами...',
    'classroom.say_something': 'Скажите что-нибудь всем...',
    'classroom.leave_confirm_title': 'Покинуть класс?',
    'classroom.leave_confirm_desc': 'Вы уверены, что хотите завершить учебную сессию?',
    'classroom.live_stream': 'Прямой эфир',
    'classroom.you_on_stage': 'ВЫ • На сцене',
    'classroom.rec': 'ЗАПИСЬ',
    'classroom.ai_trans_log': 'Журнал ИИ-перевода в реальном времени',
    'classroom.listening_translating': 'Прослушивание и перевод речи...',
    'classroom.start_conversation': 'Начните беседу. Ваше сообщение появится в виде бегущей строки!',
    'classroom.hand_raise_required': 'Нужно поднять руку',
    'classroom.mute_mic': 'Выключить мик',
    'classroom.unmute_mic': 'Включить мик',
    'classroom.stop_video': 'Выключить видео',
    'classroom.start_video': 'Включить видео',
    'classroom.raise_hand': 'Поднять руку',
    'classroom.waiting_teacher': 'Ожидание учителя...',
    'classroom.on_stage': 'На сцене',
    'classroom.stop_recording': 'Остановить запись',
    'classroom.record_lesson': 'Записать урок',
    'classroom.exit_fullscreen': 'Выход из полноэкранного режима',
    'login.subtitle': 'Продолжите свое путешествие по освоению китайского языка',
    'login.email_label': 'Электронная почта',
    'login.password_label': 'Пароль',
    'login.forgot_password': 'Забыли пароль?',
    'login.continue_with': 'или продолжить через',
    'login.no_account': 'Нет аккаунта?',
    'register.subtitle': 'Начните свой путь к глобальному общению',
    'register.full_name': 'Полное имя',
    'register.student': 'Студент',
    'register.teacher': 'Учитель',
    'register.terms': 'Я принимаю Условия использования и Политику конфиденциальности.',
    'register.get_started': 'Начать',
    'register.already_account': 'Уже есть аккаунт?',
    'reports.title': 'Аналитика успеваемости',
    'reports.subtitle': 'Глубокий анализ вовлеченности студентов и эффективности программы.',
    'reports.export': 'Экспорт CSV',
    'reports.engagement_rate': 'Рейтинг вовлеченности',
    'reports.proficiency_level': 'Средний уровень владения',
    'reports.certificates': 'Выдано сертификатов',
    'reports.active_time': 'Активное время обучения',
    'reports.accuracy': 'Точность оценки',
    'reports.last_7_days': 'Последние 7 дней',
    'reports.last_30_days': 'Последние 30 дней',
    'reports.daily_avg': 'Среднее за день',
    'reports.efficacy_title': 'Эффективность по курсам',
    'reports.filter_courses': 'Фильтр курсов...',
    'reports.table_module': 'Модуль курса',
    'reports.table_score': 'Средний балл',
    'reports.table_completion': 'Процент завершения',
    'reports.table_trend': 'Тренд',
    'reports.stable': 'Стабильно',
    'reports.at_risk': 'В группе риска',
    'students.title': 'Активные студенты',
    'students.subtitle': 'Следите за прогрессом и вовлеченностью в ваших классах.',
    'students.search_placeholder': 'Поиск студентов...',
    'students.table_student': 'Студент',
    'students.table_engagement': 'Вовлеченность',
    'students.table_attendance': 'Посещаемость',
    'students.table_status': 'Статус',
    'students.table_actions': 'Действия',
    'students.active_label': 'Активен',
    'students.on_track': 'В графике',
    'students.at_risk': 'В зоне риска',
    'students.excellence': 'Отлично',
    'students.total_students': 'Всего студентов',
    'students.avg_attendance': 'Средняя посещаемость',
    'students.students_at_risk': 'Студенты в зоне риска',
    'time.ago': 'назад',
    'time.hours': 'ч.',
    'time.minutes': 'мин.',
    'time.days': 'дн.',
    'time.now': 'Сейчас',
    'homework.pass': 'ЗАЧЕНО',
    'homework.fail': 'НЕЗАЧЕНО',
    'homework.today': 'Сегодня',
    'homework.no_assignments': 'Для этого занятия еще нет заданий.',
    'teacher.weekly_engagement': 'Еженедельное вовлечение',
    'teacher.quiz_completion': 'Завершение тестов',
    'teacher.student_satisfaction': 'Удовлетворенность студентов',
    'teacher.action_needed': 'Требуется действие',
    'teacher.homework_reminder': '12 студентов еще не сдали домашнее задание по главе 3.',
    'teacher.remind_all': 'НАПОМНИТЬ ВСЕМ',
    'teacher.recent_activity': 'Последние действия',
    'teacher.activity_submitted': 'сдал(а)',
    'teacher.activity_enrolled': 'записался(ась) на',
    'teacher.activity_messaged': 'отправил(а) сообщение по',
    'teacher.view_audit': 'ПОСМОТРЕТЬ ВЕСЬ ЖУРНАЛ',
  },
  kk: {
    'nav.home': 'Басты бет',
    'nav.courses': 'Курстар',
    'nav.vocabulary': 'Сөздік',
    'nav.homework': 'Үй тапсырмасы',
    'nav.classroom': 'Онлайн-сабақ',
    'nav.students': 'Студенттер',
    'nav.reports': 'Есептер',
    'nav.login': 'Кіру',
    'nav.register': 'Тегін тіркелу',
    'app.logo.title': 'LingoBridge',
    'app.logo.subtitle': 'Әлем азаматтарына арналған қытай тілі',
    'nav.methodology': 'Әдістеме',
    'nav.teachers': 'Оқытушылар',
    'hero.title': 'Қытай тілін осы жерден бастап үйреніңіз',
    'hero.subtitle': 'Орыс тілділерге арналған батыру және ойластырылған дизайны бар арнайы қытай тілі курсы.',
    'hero.student_btn': 'Мен студентпін, оқығым келеді',
    'hero.teacher_btn': 'Мен оқытушымын',
    'hero.login_prompt': 'Тіркелгенсіз бе?',
    'dashboard.welcome': 'Қош келдіңіз',
    'dashboard.quote': '«Оқу - бұл әдет... Шекараңызды кеңейтіп, қытай тілін әр иероглиф бойынша меңгеріңіз».',
    'dashboard.continue': 'Оқуды жалғастыру',
    'dashboard.schedule': 'Кестені көру',
    'dashboard.streak': 'Қазіргі серия',
    'dashboard.points': 'Жалпы ұпайлар',
    'dashboard.tasks': 'Бүгінгі тапсырмалар',
    'dashboard.view_all': 'Барлық тапсырмалар',
    'footer.desc': 'LingoBridge-тің марапатқа ие оқу бағдарламасымен мәдени алшақтықты жойып, болашақ тілін меңгеріңіз.',
    'footer.education': 'Білім',
    'footer.support': 'Қолдау',
    'footer.legal': 'Құқықтық ақпарат',
    'footer.courses_syllabus': 'Курстар және бағдарлама',
    'footer.teachers': 'Мұғалімдер порталы',
    'footer.mobile': 'Мобильді қосымша',
    'footer.help': 'Анықтама орталығы',
    'footer.contact': 'Бізбен байланысыңыз',
    'footer.docs': 'Құжаттама',
    'footer.privacy': 'Құпиялылық саясаты',
    'footer.terms': 'Пайдалану шарттары',
    'partners.title': 'Жаһандық академиялық серіктестер',
    'steps.title': 'Еркін сөйлеуге жол',
    'steps.subtitle': '3 қарапайым қадаммен мақсатқа жету',
    'stats.learners': 'Белсенді студенттер',
    'stats.partners': 'Серіктес мектептер',
    'feature.step1.title': '1. Алдын ала оқу',
    'feature.step1.desc': 'Сөздік карталар, мағына түсіндірмелері және иероглиф жазу анимациясы.',
    'feature.step2.title': '2. Онлайн-сабақтар',
    'feature.step2.desc': 'Мұғаліммен тікелей сабақтар, интерактивті қарым-қатынас, ешқандай зерігу жоқ.',
    'feature.step3.title': '3. Практика және ұпайлар',
    'feature.step3.desc': 'Айтылымды талдау, рейтингтер, ойын тапсырмалары — әр қадам сайын ілгерілеу.',
    'showcase.recording.title': 'Сөйлеуді тану',
    'showcase.recording.desc': 'ИИ арқылы айтылымыңызды нақты уақытта жазып, талдаңыз.',
    'showcase.meeting.title': 'Онлайн-конференциялар',
    'showcase.meeting.desc': 'Аудару және ақ тақталармен нақты уақыттағы интерактивті оқыту.',
    'showcase.multi_device.title': 'Құрылғыларды синхрондау',
    'showcase.multi_device.desc': 'Оқу барысын сақтай отырып, Mac, iPad және iPhone арасында ауысыңыз.',
    'classroom.recording': 'Жазу',
    'classroom.upload_pdf': 'PDF жүктеу',
    'classroom.clear_canvas': 'Сияны тазарту',
    'classroom.start_screen_hint': 'Жергілікті режимді бастау үшін экранды бөлісуді бастаңыз.',
    'schedule.replays': 'Тарих және жазбалар',
    'schedule.view_replay': 'Қайталап көру',
    'classroom.participants': 'Қатысушылар',
    'classroom.chat': 'Чат',
    'classroom.poll': 'Сауалнама',
    'classroom.translate': 'Аудару',
    'classroom.settings': 'Параметрлер',
    'classroom.mute': 'Дыбысты өшіру',
    'classroom.camera': 'Камераны қосу',
    'classroom.screen': 'Экранды көрсету',
    'classroom.stop_share': 'Бөлісуді тоқтату',
    'classroom.leave': 'Кластан шығу',
    'classroom.topic': 'Күн тақырыбы',
    'classroom.subtitles': 'Нақты уақыттағы субтитрлер',
    'classroom.bilingual': 'ҚЫТ / АҒЫЛ',
    'classroom.students': 'Студенттер',
    'classroom.active': 'Белсенді',
    'classroom.message_placeholder': 'Хабарлама жазу...',
    'classroom.poll_question': "'大家好' үшін дұрыс пиньинь қандай?",
    'vocab.study_modes': 'Оқу режимдері',
    'vocab.search_placeholder': 'Сөздерді іздеу...',
    'vocab.launch_game': 'Ойынды бастау',
    'vocab.start_review': 'Қайталауды бастау',
    'classroom.course_title': 'Жаңадан бастаушыларға арналған қытай тілі (1-бөлім)',
    'dashboard.greeting_teacher': 'Сәлеметсіз бе, Ли Лаоши!',
    'dashboard.greeting_student': 'Сәлем, Анна!',
    'dashboard.overview': 'Бүгінгі кестеңізге шолу.',
    'dashboard.view_all_action': 'Барлығын көру',
    'dashboard.schedule_label': 'Бүгінгі тапсырмалар',
    'homework.title': 'Сөйлеу практикасы',
    'homework.active_task': 'Белсенді тапсырма',
    'homework.subtitle': 'Келесі сөйлемді микрофонға анық оқыңыз.',
    'homework.due': 'Мерзімі',
    'homework.pages': 'Беттер',
    'homework.tip': 'Кеңес: тондардың жүйелілігіне және еркіндігіне назар аударыңыз.',
    'homework.recording': 'ЖАЗУ...',
    'homework.ready': 'Практикаға дайынсыз ба',
    'homework.latest': 'Соңғы жазбалар (макс. 3)',
    'homework.score': 'Ұпайлар',
    'homework.ai_eval': 'ИИ бағалауы',
    'homework.total_score': 'ҰПАЙЛАР',
    'homework.excellent': 'Керемет!',
    'homework.great': 'Жақсы жұмыс!',
    'homework.keep_practicing': 'Практиканы жалғастырыңыз!',
    'homework.eval_desc': 'Сізде еркін сөйлеу деңгейі жақсы. Нақты иероглифтердің айтылымына назар аударыңыз.',
    'homework.fluency': 'Еркіндік',
    'homework.tone': 'Тон дәлдігі',
    'homework.pronunciation': 'Айтылым',
    'homework.completeness': 'Толықтығы',
    'homework.grammar': 'Грамматика және түзетулер',
    'homework.tone_deviation': 'Тоннан ауытқу',
    'homework.tone_desc': 'Кішкене ауытқу анықталды. Тонды айқындауға тырысыңыз.',
    'homework.learning_tip': 'Оқу кеңесі',
    'homework.learning_desc': 'Тыныс алуға назар аударып, қайта жазыңыз.',
    'homework.model_answer': 'Жауап нұсқасы',
    'homework.prev': 'Алдыңғы сұрақ',
    'homework.explain': 'Түсіндіру',
    'homework.greetings_basics': 'Сәлемдесу және негіздер',
    'homework.family_jobs': 'Отбасы және жұмыс',
    'homework.daily_routine': 'Күнделікті жұмыс',
    'homework.shopping': 'Сауда жасау',
    'homework.more_coming': 'Жақында көбірек сабақтар болады',
    'homework.back_path': 'Жолға оралу',
    'homework.progress': 'Прогресс',
    'homework.lesson_greet': 'Негізгі сәлемдесулер',
    'homework.lesson_intro': 'Өзім туралы',
    'homework.lesson_family': 'Отбасы мүшелері',
    'homework.lesson_mom': 'Анамды сипаттау',
    'homework.lesson_family_para': 'Қысқа мақала: Менің отбасым',
    'homework.lesson_time': 'Уақыт пен әрекеттер',
    'homework.lesson_schedule': 'Менің кестем',
    'homework.save': 'Прогресті сақтау',
    'homework.next': 'Келесі тапсырма',
    'homework.path_title': 'Менің оқу жолым',
    'homework.path_desc': 'Мектеп бағдарламасына сәйкес тапсырмаларды орындаңыз.',
    'homework.unit': 'Модуль',
    'homework.lesson': 'Сабақ',
    'homework.start_task': 'Тапсырманы бастау',
    'homework.type.speaking': 'Сөйлеу практикасы',
    'homework.type.vocab': 'Сөздік жаттығулары',
    'homework.type.reading': 'Оқығанды түсіну',
    'homework.completed': 'Аяқталды',
    'homework.locked': 'Блокталған',
    'homework.stats.title': 'Статистика',
    'homework.stats.mistakes': 'Қателер',
    'homework.stats.favorites': 'Таңдаулылар',
    'homework.stats.records': 'Тарих',
    'homework.stats.graph': 'Білім графы',
    'homework.stats.syllabus': 'Оқу жоспары',
    'homework.stats.mindmap': 'Интеллект-карта',
    'homework.stats.ranking': 'Рейтингтер',
    'homework.stats.streak': 'Ударный режим',
    'homework.stats.points': 'Тәжірибе ұпайлары',
    'vocab.study_now': 'Қазір үйрену',
    'vocab.review': 'Қайталау',
    'vocab.mastery': 'Меңгеру',
    'vocab.learning_title': 'Оқу сессиясы',
    'vocab.correct': 'Дұрыс!',
    'vocab.incorrect': 'Бұрыс',
    'vocab.check': 'Тексеру',
    'vocab.continue': 'Жалғастыру',
    'vocab.finish': 'Сессияны аяқтау',
    'vocab.translate_to_ru': 'Орыс тіліне аудару',
    'vocab.translate_to_zh': 'Қытай тіліне аудару',
    'vocab.pronounce': 'Сөзді айтыңыз',
    'vocab.phonetic_group': 'Фонетикалық топ',
    'schedule.sync': 'Google күнтізбесін синхрондау',
    'schedule.syncing': 'Синхрондау...',
    'schedule.synced': 'Google күнтізбесімен синхрондалды',
    'schedule.deadlines': 'Дедлайндар',
    'schedule.upcoming': 'Келесі тікелей сессиялар',
    'schedule.agenda': 'Күн тәртібі',
    'schedule.week': 'Апта',
    'schedule.join_class': 'Тікелей сабаққа қосылу',
    'schedule.details': 'Толығырақ',
    'schedule.add_personal': 'Жеке кестені қосу',
    'schedule.tomorrow': 'Ертең',
    'schedule.month_year': 'Сәуір 2026',
    'schedule.days_short': 'Ж Д С С Б Ж С',
    'schedule.live_badge': 'Тікелей',
    'schedule.instr': 'Нұсқаушы',
    'notification.title': 'Хабарландырулар',
    'notification.mark_all': 'Барлығын оқылған деп белгілеу',
    'notification.view_all': 'Барлық хабарландыруларды көру',
    'course.basic': 'Жаңадан бастаушыларға арналған қытай тілі (1-бөлім)',
    'course.vocab': 'HSK 3 сөздігін қайталау',
    'course.culture': 'Қытай мәдениеті мен тарихы',
    'course.quiz': 'Сөздік тесті',
    'stats.days': 'күн',
    'stats.pts': 'ұпай',
    'stats.starting_in': 'Басталуына',
    'stats.minutes': 'минут қалды',
    'dashboard.join_classroom': 'Классқа кіру',
    'dashboard.task.preview': 'Алдын ала тапсырма',
    'dashboard.task.prep_family': 'Дайындық: 3-сабақ «Отбасы»',
    'dashboard.task.prep_desc': 'Келесі сабақтың жаңа сөздігі мен грамматикалық құрылымдарын үйреніңіз.',
    'dashboard.task.start': 'Тапсырманы бастау',
    'dashboard.task.live_soon': 'Жақында тікелей эфирде',
    'dashboard.task.reminder': 'Сабақ туралы ескерту',
    'dashboard.task.live_lesson': '14:00 Онлайн-сабақ: HSK 3 грамматикасы',
    'dashboard.task.homework': 'Үй тапсырмасы',
    'dashboard.task.review_ch2': 'Қайталау: 2-тарауды түсіну',
    'dashboard.task.review_desc': 'Алдыңғы модульдегі тыңдалым және оқылым жаттығуларын орындаңыз.',
    'dashboard.task.submit': 'Тапсырманы тапсыру',
    'dashboard.quick_access': 'Жылдам қол жеткізу',
    'dashboard.my_schedule': 'Менің кестем',
    'dashboard.week_stats': 'Апталық статистика',
    'dashboard.char_lab': 'Иероглифтер лабораториясы',
    'dashboard.live_events': 'Тікелей шаралар',
    'dashboard.ranking': 'Апталық рейтинг',
    'dashboard.leaderboard': 'Толық рейтинг кестесі',
    'showcase.optimized_desc': 'Сіздің өміріңіздегі кез келген құрылғыға оңтайландырылған үздіксіз білім алу тәжірибесі.',
    'showcase.lesson_label': '1-сабақ',
    'showcase.now_live': 'Тікелей эфир',
    'showcase.lesson_title': 'Кешкі HSK қарқынды курсы',
    'showcase.cloud_presence': 'Бұлтты синхрондау: Белсенді',
    'showcase.ai_core': 'ИИ Ядросы',
    'showcase.low_latency': 'Төмен кідіріс',
    'showcase.multi_lang': 'Көптілділік',
    'showcase.phonetic': 'mā ma',
    'showcase.meaning': 'Ана',
    'showcase.example_zh': 'Zhè shì wǒ māma.',
    'showcase.example_en': '"Бұл менің анам."',
    'footer.rights': '© 2024 LingoBridge Learning Systems. Барлық құқықтар қорғалған.',
    'vocab.repo_desc': 'Сіздің жеке қытай тілі терминдерінің қоймасы.',
    'vocab.spaced_active': 'Аралық қайталау белсенді',
    'vocab.mastered': 'Меңгерілген',
    'vocab.learning': 'Үйренуде',
    'vocab.new': 'Жаңа',
    'vocab.rhyme': 'Ұйқас',
    'vocab.cluster': 'Сөздер тобы',
    'vocab.launch': 'Бастау',
    'vocab.add_word': 'Сөз қосу',
    'vocab.recommended': 'Сізге ұсынылған',
    'vocab.master_title': 'Аралық қайталау арқылы 15 жаңа сөзді меңгеріңіз',
    'vocab.ai_analyze': 'Біздің ИИ сіздің соңғы қателіктеріңізді талдады. Бүгінгі назарда:',
    'vocab.start_ai': 'ИИ қайталауды бастау',
    'vocab.next_review': 'Келесі қайталау: Ертерң',
    'vocab.weekly_rank': 'Апталық рейтинг: #12',
    'vocab.session_complete': 'Сессия аяқталды!',
    'vocab.session_desc': 'Сіз осы сессияда {score} сұрақты меңгердіңіз.',
    'vocab.accuracy': 'Дәлдік',
    'vocab.exp_gained': 'Тәжірибе жиналды',
    'vocab.hold_speak': 'Сөйлеу үшін басып тұрыңыз',
    'vocab.pron_great': 'Керемет айтылым!',
    'vocab.pron_well': 'Жақсы! Келесіге көшеміз.',
    'vocab.pron_low': 'Ұпай 80-нен төмен. Қайта көріңіз!',
    'vocab.correct_is': 'Дұрысы:',
    'course.my_courses': 'Менің курстарым',
    'course.manage': 'Оқу материалдары мен белсенді кластарды басқарыңыз.',
    'course.create': 'Жаңа курс жасау',
    'course.title_placeholder': 'Курс атауы',
    'course.upload': 'Жүктеу',
    'course.upload_hint': 'Курсты таңдап, беттер үшін .pptx/.pdf немесе жаттығулар үшін .xlsx жүктеңіз.',
    'course.upload_result': '{filename} жүктелді. Беттер: {pages}, жаттығулар: {exercises}.',
    'course.loading': 'Курстар жүктелуде...',
    'course.load_failed': 'Курстар жүктелмеді. 3001 портындағы backend іске қосылғанын тексеріңіз.',
    'course.created': 'Курс жасалды.',
    'course.create_failed': 'Курс жасау сәтсіз аяқталды.',
    'course.upload_failed': 'Жүктеу сәтсіз аяқталды.',
    'course.untitled': 'Жаңа қытай тілі курсы',
    'course.no_description': 'Әзірге сипаттама жоқ.',
    'course.exercises': 'Жаттығулар',
    'course.upload_courseware': 'Материалдарды жүктеу',
    'course.upload_excel': 'Excel жүктеу',
    'course.excel_result': '{filename} жүктелді. Тапсырмалар: {tasks}, сөздер: {vocab}.',
    'course.excel_warnings': 'Ескертулер',
    'course.published': 'Жарияланған',
    'course.draft': 'Черновик',
    'course.edit': 'Мазмұнды өңдеу',
    'course.enter': 'Классқа кіру',
    'course.reports': 'Оқу есептері',
    'course.add_new': 'Жаңа курс қосу',
    'course.custom_syllabus': 'Жеке оқу жоспарын жасау',
    'course.spring': 'Көктемгі семестр 2024',
    'course.autumn': 'Күзгі семестр 2023',
    'course.summer': 'Жаз 2024',
    'course.advanced': 'Жоғары деңгейлі қытай тілі (HSK 4 дайындық)',
    'course.business': 'Кәсіби мамандарға арналған іскерлік қытай тілі',
    'course.hsk1_unit4': 'Бастаушы қытай тілі HSK 1 - 4-бөлім',
    'course.business_prep': 'Іскерлік қытай тіліне дайындық',
    'course.workshop': 'Интерактивті воркшоп',
    'course.level1': '1-деңгей',
    'course.level4': '4-деңгей',
    'course.mixed': 'Аралас деңгей',
    'classroom.end_confirm_title': 'Барлығы үшін сабақты аяқтау керек пе?',
    'classroom.end_confirm_desc': 'Бұл барлық студенттер үшін класты жабады. Сенімдісіз бе?',
    'classroom.end_btn': 'Сабақты аяқтау',
    'classroom.cancel': 'Бас тарту',
    'classroom.end_poll': 'Сауалнаманы аяқтау',
    'classroom.interactive_assessment': 'Интерактивті бағалау',
    'classroom.ppt_locked': 'Студенттер үшін PPT бұғатталған',
    'classroom.ppt_unlocked': 'Студенттер PPT-ні көре алады',
    'classroom.key_vocab': 'Күннің негізгі лексикасы',
    'classroom.transcript_title': 'AI транскрипциясы мен аудармасының нақты уақыттағы жазбасы',
    'classroom.cn_ru_active': 'CN-RU арнасы белсенді',
    'classroom.system_ready': 'Жүйе дайын • Сөйлеуді талдау...',
    'classroom.mic_studio': 'СТУДИЯЛЫҚ МИК',
    'classroom.mic_off': 'МИК ӨШІРУЛІ',
    'classroom.screen_sharing': 'Экранды көрсету белсенді',
    'classroom.presentation_locked': 'Презентация бұғатталған',
    'classroom.live_discussion': 'Тікелей талқылау',
    'classroom.waiting_interaction': 'Студенттермен өзара әрекеттесуді күтуде...',
    'classroom.say_something': 'Барлығына бірдеңе айтыңыз...',
    'classroom.leave_confirm_title': 'Кластан шығу керек пе?',
    'classroom.leave_confirm_desc': 'Оқу сессиясын аяқтағыңыз келетініне сенімдісіз бе?',
    'classroom.live_stream': 'Тікелей эфир',
    'classroom.you_on_stage': 'СІЗ • Сахнадасыз',
    'classroom.rec': 'ЖАЗУ',
    'classroom.ai_trans_log': 'AI нақты уақыттағы аударма журналы',
    'classroom.listening_translating': 'Сөйлеуді тыңдау және аудару...',
    'classroom.start_conversation': 'Әңгімені бастаңыз. Сіздің хабарламаңыз弹幕 түрінде де пайда болады!',
    'classroom.hand_raise_required': 'Қол көтеру қажет',
    'classroom.mute_mic': 'Микрофонды өшіру',
    'classroom.unmute_mic': 'Микрофонды қосу',
    'classroom.stop_video': 'Бейнебаянды тоқтату',
    'classroom.start_video': 'Бейнебаянды бастау',
    'classroom.raise_hand': 'Қол көтеру',
    'classroom.waiting_teacher': 'Мұғалімді күтуде...',
    'classroom.on_stage': 'Сахнада',
    'classroom.stop_recording': 'Жазуды тоқтату',
    'classroom.record_lesson': 'Сабақты жазу',
    'classroom.exit_fullscreen': 'Толық экраннан шығу',
    'login.subtitle': 'Қытай тілін меңгеру жолын жалғастырыңыз',
    'login.email_label': 'Электронды пошта',
    'login.password_label': 'Құпиясөз',
    'login.forgot_password': 'Құпиясөзді ұмыттыңыз ба?',
    'login.continue_with': 'немесе жалғастыру',
    'login.no_account': 'Тіркелмегенсіз бе?',
    'register.subtitle': 'Жаһандық қарым-қатынасқа жол бастаңыз',
    'register.full_name': 'Толық аты-жөні',
    'register.student': 'Студент',
    'register.teacher': 'Мұғалім',
    'register.terms': 'Мен Қызмет көрсету шарттарымен және Құпиялылық саясатымен келісемін.',
    'register.get_started': 'Бастау',
    'register.already_account': 'Тіркелгенсіз бе?',
    'reports.title': 'Үлгерім аналитикасы',
    'reports.subtitle': 'Студенттердің қатысуы мен бағдарламаның тиімділігін терең талдау.',
    'reports.export': 'CSV экспорттау',
    'reports.engagement_rate': 'Класс қатысу деңгейі',
    'reports.proficiency_level': 'Орташа еркіндік деңгейі',
    'reports.certificates': 'Берілген сертификаттар',
    'reports.active_time': 'Белсенді оқу уақыты',
    'reports.accuracy': 'Бағалау дәлдігі',
    'reports.last_7_days': 'Соңғы 7 күн',
    'reports.last_30_days': 'Соңғы 30 күн',
    'reports.daily_avg': 'Күнделікті орташа',
    'reports.efficacy_title': 'Курс бойынша тиімділік',
    'reports.filter_courses': 'Курстарды сүзу...',
    'reports.table_module': 'Курс модулі',
    'reports.table_score': 'Орташа ұпай',
    'reports.table_completion': 'Аяқталу деңгейі',
    'reports.table_trend': 'Тренд',
    'reports.stable': 'Тұрақты',
    'reports.at_risk': 'Қауіп тобында',
    'students.title': 'Белсенді студенттер',
    'students.subtitle': 'Сабақтарыңыздағы ілгерілеу мен қатысуды бақылаңыз.',
    'students.search_placeholder': 'Студенттерді іздеу...',
    'students.table_student': 'Студент',
    'students.table_engagement': 'Қатысуы',
    'students.table_attendance': 'Сабаққа қатысуы',
    'students.table_status': 'Статус',
    'students.table_actions': 'Әрекеттер',
    'students.active_label': 'Белсенді',
    'students.on_track': 'Дұрыс жолда',
    'students.at_risk': 'Қауіп тобында',
    'students.excellence': 'Өте жақсы',
    'students.total_students': 'Студенттер саны',
    'students.avg_attendance': 'Орташа қатысуы',
    'students.students_at_risk': 'Қауіп тобындағы студенттер',
    'time.ago': 'бұрын',
    'time.hours': 'сағат',
    'time.minutes': 'минут',
    'time.days': 'күн',
    'time.now': 'Қазір',
    'homework.pass': 'ӨТТІ',
    'homework.fail': 'ӨТПЕДІ',
    'homework.today': 'Бүгін',
    'homework.no_assignments': 'Бұл сабақ үшін әлі тапсырмалар жоқ.',
    'teacher.weekly_engagement': 'Апталық белсенділік',
    'teacher.quiz_completion': 'Тестті аяқтау',
    'teacher.student_satisfaction': 'Студенттердің ризашылығы',
    'teacher.action_needed': 'Әрекет қажет',
    'teacher.homework_reminder': '12 студент әлі 3-бөлімнің үй тапсырмасын тапсырған жоқ.',
    'teacher.remind_all': 'БАРЛЫҒЫНА ЕСКЕРТУ',
    'teacher.recent_activity': 'Соңғы әрекеттер',
    'teacher.activity_submitted': 'тапсырды',
    'teacher.activity_enrolled': 'тіркелді',
    'teacher.activity_messaged': 'хабарлама жіберді',
    'teacher.view_audit': 'ТОЛЫҚ ЖУРНАЛДЫ КӨРУ',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
