import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'en' | 'zh' | 'ru';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    'nav.home': 'Home',
    'nav.courses': 'Courses',
    'nav.vocabulary': 'Vocabulary',
    'nav.homework': 'Homework',
    'nav.classroom': 'Live Class',
    'nav.students': 'Students',
    'nav.reports': 'Reports',
    'nav.login': 'Login',
    'nav.register': 'Free Registration',
    'app.logo.title': 'HanBridge',
    'app.logo.subtitle': 'Chinese for Global Citizens',
    'nav.methodology': 'Methodology',
    'nav.teachers': 'Teachers',
    'hero.title': 'Learn Chinese Starting from Here',
    'hero.subtitle': 'Specialized Chinese course for Russian speakers with immersion and thoughtful design.',
    'hero.student_btn': "I'm a Student",
    'hero.teacher_btn': "I'm a Teacher",
    'hero.login_prompt': 'Already have an account?',
    'dashboard.welcome': 'Welcome back',
    'dashboard.quote': '"Learning is a habit... Keep pushing your boundaries and master Mandarin one character at a time."',
    'dashboard.continue': 'Continue Learning',
    'dashboard.schedule': 'View Schedule',
    'dashboard.streak': 'Current Streak',
    'dashboard.points': 'Total Points',
    'dashboard.tasks': "Today's Tasks",
    'dashboard.view_all': 'View All Tasks',
    'footer.desc': 'Bridge the cultural gap and master the language of the future with HanBridge\'s award-winning curriculum.',
    'footer.education': 'Education',
    'footer.support': 'Support',
    'footer.legal': 'Legal',
    'footer.courses_syllabus': 'Courses & Syllabus',
    'footer.teachers': 'Teacher Portals',
    'footer.mobile': 'Mobile App',
    'footer.help': 'Help Center',
    'footer.contact': 'Contact Us',
    'footer.docs': 'Documentation',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    'partners.title': 'Global Academic Partners',
    'steps.title': 'Your Path to Fluency',
    'steps.subtitle': 'Achievement in 3 simple steps',
    'stats.learners': 'Active Learners',
    'stats.partners': 'Partner Schools',
    'feature.step1.title': '1. Pre-learning',
    'feature.step1.desc': 'Vocabulary cards, meaning explanations, and stroke animations.',
    'feature.step2.title': '2. Online Classes',
    'feature.step2.desc': 'Live classes with teachers, interactive communication, no boredom.',
    'feature.step3.title': '3. Practice & Points',
    'feature.step3.desc': 'Pronunciation analysis, rankings, game tasks - progress with every step.',
    'showcase.recording.title': 'Speech Recognition',
    'showcase.recording.desc': 'Record and analyze your pronunciation in real-time with AI-powered feedback.',
    'showcase.meeting.title': 'Live Meeting Room',
    'showcase.meeting.desc': 'Interactive classroom experience with real-time translation and whiteboards.',
    'showcase.multi_device.title': 'Multi-platform Sync',
    'showcase.multi_device.desc': 'Seamlessly switch between Mac, iPad, and iPhone while keeping your progress.',
    'classroom.recording': 'Recording',
    'classroom.participants': 'Participants',
    'classroom.chat': 'Chat',
    'classroom.poll': 'Live Poll',
    'classroom.translate': 'Translate',
    'classroom.settings': 'Settings',
    'classroom.mute': 'Mute Mic',
    'classroom.camera': 'Toggle Camera',
    'classroom.screen': 'Share Screen',
    'classroom.leave': 'Leave Class',
    'classroom.topic': 'Daily Topic',
    'classroom.subtitles': 'Real-time Subtitles',
    'classroom.bilingual': 'ZH / EN',
    'classroom.students': 'Students',
    'classroom.active': 'Active',
    'classroom.message_placeholder': 'Message classroom...',
    'classroom.poll_question': "What is the correct Pinyin for '大家好'?",
    'vocab.study_modes': 'Study Modes',
    'vocab.search_placeholder': 'Search words...',
    'vocab.launch_game': 'Launch Game',
    'vocab.start_review': 'Start Review',
    'classroom.course_title': 'Basic Chinese (Part 1)',
    'dashboard.greeting_teacher': 'Bonjour, Instructor Li!',
    'dashboard.greeting_student': 'Hello, Anna Zhang!',
    'dashboard.overview': 'Here is what\'s happening with your classes today.',
    'dashboard.view_all_action': 'View All',
    'dashboard.schedule_label': 'Daily Schedule',
    'homework.title': 'Speaking Practice',
    'homework.active_task': 'Active Task',
    'homework.subtitle': 'Please read the following sentence clearly into your microphone.',
    'homework.due': 'Due',
    'homework.today': 'Today',
    'homework.pages': 'Pages',
    'homework.tip': 'Tip: Focused on tone consistency and flow.',
    'homework.recording': 'RECORDING...',
    'homework.ready': 'Ready to Practice',
    'homework.latest': 'Latest Recordings (Max 3)',
    'homework.score': 'Score',
    'homework.ai_eval': 'AI Evaluation',
    'homework.total_score': 'SCORE',
    'homework.excellent': 'Excellent!',
    'homework.great': 'Great Job!',
    'homework.keep_practicing': 'Keep Practicing!',
    'homework.eval_desc': 'Your fluency is superb. Focus on specific character pronunciations.',
    'homework.fluency': 'Fluency',
    'homework.tone': 'Tone Accuracy',
    'homework.pronunciation': 'Pronunciation',
    'homework.completeness': 'Completeness',
    'homework.grammar': 'Grammar & Correction',
    'homework.tone_deviation': 'Tone Deviation',
    'homework.tone_desc': 'Small deviation detected. Try to emphasize the tone.',
    'homework.learning_tip': 'Learning Tip',
    'homework.learning_desc': 'Record once more focusing on breathing.',
    'homework.model_answer': 'Model Answer',
    'homework.prev': 'Previous Question',
    'homework.explain': 'Explain',
    'homework.save': 'Save Progress',
    'homework.next': 'Next Task',
    'homework.path_title': 'My Learning Path',
    'homework.path_desc': 'Complete assignments to synchronize with your classroom curriculum.',
    'homework.unit': 'Unit',
    'homework.lesson': 'Lesson',
    'homework.start_task': 'Start Assignment',
    'homework.type.speaking': 'Speaking Practice',
    'homework.type.vocab': 'Vocabulary Drill',
    'homework.type.reading': 'Reading Comprehension',
    'homework.completed': 'Completed',
    'homework.locked': 'Locked',
    'homework.stats.title': 'Learning Stats',
    'homework.stats.mistakes': 'Mistakes',
    'homework.stats.favorites': 'Favorites',
    'homework.stats.records': 'History',
    'homework.stats.graph': 'Knowledge Graph',
    'homework.stats.syllabus': 'Course Syllabus',
    'homework.stats.mindmap': 'Mind Map',
    'homework.stats.ranking': 'Global Rankings',
    'homework.stats.streak': 'Day Streak',
    'homework.stats.points': 'Exp Points',
    'vocab.study_now': 'Study Now',
    'vocab.review': 'Review',
    'vocab.mastery': 'Mastery',
    'vocab.learning_title': 'Learning Session',
    'vocab.correct': 'Correct!',
    'vocab.incorrect': 'Incorrect',
    'vocab.check': 'Check Answer',
    'vocab.continue': 'Continue',
    'vocab.finish': 'Finish Session',
    'vocab.translate_to_ru': 'Translate to Russian',
    'vocab.translate_to_zh': 'Translate to Chinese',
    'vocab.pronounce': 'Pronounce the word',
    'vocab.phonetic_group': 'Phonetic Group Study',
  },
  zh: {
    'nav.home': '首页',
    'nav.courses': '课程',
    'nav.vocabulary': '词汇',
    'nav.homework': '作业',
    'nav.classroom': '直播课',
    'nav.students': '学生',
    'nav.reports': '报告',
    'nav.login': '登录',
    'nav.register': '免费注册',
    'app.logo.title': 'HanBridge',
    'app.logo.subtitle': '全球公民的中文桥梁',
    'nav.methodology': '教学法',
    'nav.teachers': '名师阵容',
    'hero.title': '从这里开始学习中文',
    'hero.subtitle': '专为俄语使用者设计的沉浸式中文课程，精心设计的学习体验。',
    'hero.student_btn': '我是学生，想学习',
    'hero.teacher_btn': '我是老师',
    'hero.login_prompt': '已有账号？',
    'dashboard.welcome': '欢迎回来',
    'dashboard.quote': '“学习是一种习惯... 不断挑战自我，逐字攻克中文。”',
    'dashboard.continue': '继续学习',
    'dashboard.schedule': '查看日程',
    'dashboard.streak': '当前连续',
    'dashboard.points': '总积分',
    'dashboard.tasks': '今日任务',
    'dashboard.view_all': '查看全部任务',
    'footer.desc': '通过 HanBridge 屡获殊荣的课程，弥合文化鸿沟，掌握未来的语言。',
    'footer.education': '教育',
    'footer.support': '支持',
    'footer.legal': '法律信息',
    'footer.courses_syllabus': '课程与大纲',
    'footer.teachers': '教师门户',
    'footer.mobile': '移动应用',
    'footer.help': '帮助中心',
    'footer.contact': '联系我们',
    'footer.docs': '文档',
    'footer.privacy': '隐私政策',
    'footer.terms': '服务条款',
    'partners.title': '全球学术合作伙伴',
    'steps.title': '您的流利之路',
    'steps.subtitle': '简单三步，实现跨越',
    'stats.learners': '活跃学员',
    'stats.partners': '合作院校',
    'feature.step1.title': '1. 预习阶段',
    'feature.step1.desc': '词汇卡片、释义说明和汉字书写动画。',
    'feature.step2.title': '2. 在线课程',
    'feature.step2.desc': '与老师进行直播授课，互动沟通，拒绝枯燥。',
    'feature.step3.title': '3. 练习与积分',
    'feature.step3.desc': '发音分析、排名、游戏化任务——每一步都在进步。',
    'showcase.recording.title': '语音识别录音',
    'showcase.recording.desc': '通过AI反馈实时记录并分析您的发音。',
    'showcase.meeting.title': '实时会议系统',
    'showcase.meeting.desc': '配备实时翻译和白板的互动课室体验。',
    'showcase.multi_device.title': '多端同步',
    'showcase.multi_device.desc': '在 Mac、iPad 和 iPhone 之间无缝切换，保持学习进度。',
    'classroom.recording': '录制中',
    'classroom.participants': '参会者',
    'classroom.chat': '聊天',
    'classroom.poll': '实时投票',
    'classroom.translate': '翻译',
    'classroom.settings': '设置',
    'classroom.mute': '静音麦克风',
    'classroom.camera': '切换摄像头',
    'classroom.screen': '共享屏幕',
    'classroom.leave': '离开课堂',
    'classroom.topic': '今日主题',
    'classroom.subtitles': '实时字幕',
    'classroom.bilingual': '中 / 英',
    'classroom.students': '学生',
    'classroom.active': '活跃',
    'classroom.message_placeholder': '发送消息...',
    'classroom.poll_question': "“大家好”的正确拼音是什么？",
    'vocab.study_modes': '学习模式',
    'vocab.search_placeholder': '搜索单词...',
    'vocab.launch_game': '开始游戏',
    'vocab.start_review': '开始复习',
    'classroom.course_title': '基础汉语 (第一部分)',
    'dashboard.greeting_teacher': '你好，李老师！',
    'dashboard.greeting_student': '你好，安娜！',
    'dashboard.overview': '这是您今天的教学概况。',
    'dashboard.view_all_action': '查看全部',
    'dashboard.schedule_label': '今日日程',
    'homework.title': '口语练习',
    'homework.active_task': '进行中任务',
    'homework.subtitle': '请对着麦克风清晰地读出以下句子。',
    'homework.due': '截止时间',
    'homework.today': '今日',
    'homework.pages': '页',
    'homework.tip': '提示：专注于声调的准确性和语流。',
    'homework.recording': '录音中...',
    'homework.ready': '准备好练习了吗',
    'homework.latest': '最近录音（最多3条）',
    'homework.score': '得分',
    'homework.ai_eval': 'AI 评估',
    'homework.total_score': '分数',
    'homework.excellent': '太棒了！',
    'homework.great': '做得好！',
    'homework.keep_practicing': '继续努力！',
    'homework.eval_desc': '你的流利度非常好。请多关注具体汉字的发音。',
    'homework.fluency': '流利度',
    'homework.tone': '声调准确度',
    'homework.pronunciation': '发音',
    'homework.completeness': '完整度',
    'homework.grammar': '语法与纠错',
    'homework.tone_deviation': '声调偏差',
    'homework.tone_desc': '检测到较小偏差。尝试加强该声调。',
    'homework.learning_tip': '学习提示',
    'homework.learning_desc': '再录一次，注意短句之间的呼吸。',
    'homework.model_answer': '标准答案',
    'homework.prev': '上一题',
    'homework.explain': '详解',
    'homework.save': '保存进度',
    'homework.next': '下一题',
    'homework.path_title': '我的学习路径',
    'homework.path_desc': '完成与课堂教材同步的课后作业。',
    'homework.unit': '单元',
    'homework.lesson': '课程',
    'homework.start_task': '开始作业',
    'homework.type.speaking': '口语练习',
    'homework.type.vocab': '单词巩固',
    'homework.type.reading': '阅读理解',
    'homework.completed': '已完成',
    'homework.locked': '未解锁',
    'homework.stats.title': '学习统计',
    'homework.stats.mistakes': '错题本',
    'homework.stats.favorites': '收藏本',
    'homework.stats.records': '学习记录',
    'homework.stats.graph': '知识图谱',
    'homework.stats.syllabus': '课程大纲',
    'homework.stats.mindmap': '思维导图',
    'homework.stats.ranking': '各校排名',
    'homework.stats.streak': '连续学习',
    'homework.stats.points': '经验值',
    'vocab.study_now': '立即学习',
    'vocab.review': '复习',
    'vocab.mastery': '掌握度',
    'vocab.learning_title': '学习环节',
    'vocab.correct': '正确！',
    'vocab.incorrect': '不正确',
    'vocab.check': '检查',
    'vocab.continue': '继续',
    'vocab.finish': '结束环节',
    'vocab.translate_to_ru': '翻译成俄语',
    'vocab.translate_to_zh': '翻译成中文',
    'vocab.pronounce': '读出这个单词',
    'vocab.phonetic_group': '音韵分组学习',
  },
  ru: {
    'nav.home': 'Главная',
    'nav.courses': 'Курсы',
    'nav.vocabulary': 'Словарь',
    'nav.homework': 'Домашнее задание',
    'nav.classroom': 'Онлайн-урок',
    'nav.students': 'Студенты',
    'nav.reports': 'Отчеты',
    'nav.login': 'Войти',
    'nav.register': 'Бесплатная регистрация',
    'app.logo.title': 'HanBridge',
    'app.logo.subtitle': 'Китайский для граждан мира',
    'nav.methodology': 'Методология',
    'nav.teachers': 'Преподаватели',
    'hero.title': 'Изучайте китайский начиная отсюда',
    'hero.subtitle': 'Специальный курс китайского языка для русскоговорящих с погружением и продуманным дизайном.',
    'hero.student_btn': 'Я студент, хочу учиться',
    'hero.teacher_btn': 'Я преподаватель',
    'hero.login_prompt': 'Уже есть аккаунт?',
    'dashboard.welcome': 'С возвращением',
    'dashboard.quote': '«Обучение - это привычка... Продолжайте расширять свои границы и осваивать китайский язык по одному иероглифу за раз».',
    'dashboard.continue': 'Продолжить обучение',
    'dashboard.schedule': 'Посмотреть расписание',
    'dashboard.streak': 'Текущая серия',
    'dashboard.points': 'Всего баллов',
    'dashboard.tasks': 'Задачи на сегодня',
    'dashboard.view_all': 'Все задачи',
    'footer.desc': 'Преодолевайте культурный разрыв и осваивайте язык будущего с отмеченной наградами учебной программой HanBridge.',
    'footer.education': 'Продукт',
    'footer.support': 'Поддержка',
    'footer.legal': 'Правовая информация',
    'footer.courses_syllabus': 'Курсы и программа',
    'footer.teachers': 'Портал для учителей',
    'footer.mobile': 'Мобильное приложение',
    'footer.help': 'Справочный центр',
    'footer.contact': 'Связаться с нами',
    'footer.docs': 'Документация',
    'footer.privacy': 'Политика конфиденциальности',
    'footer.terms': 'Условия использования',
    'partners.title': 'Глобальные академические партнеры',
    'steps.title': 'Ваш путь к беглости',
    'steps.subtitle': 'Достижение цели за 3 простых шага',
    'stats.learners': 'Активные студенты',
    'stats.partners': 'Партнерские школы',
    'feature.step1.title': '1. Предварительное изучение',
    'feature.step1.desc': 'Словарные карточки, объяснения значений и анимация написания иероглифов.',
    'feature.step2.title': '2. Онлайн-уроки',
    'feature.step2.desc': 'Живые уроки с преподавателем, интерактивное общение, никакой скуки.',
    'feature.step3.title': '3. Практика и баллы',
    'feature.step3.desc': 'Анализ произношения, рейтинги, игровые задания — прогресс с каждым шагом.',
    'showcase.recording.title': 'Распознавание речи',
    'showcase.recording.desc': 'Записывайте и анализируйте свое произношение в реальном времени с помощью ИИ.',
    'showcase.meeting.title': 'Онлайн-конференции',
    'showcase.meeting.desc': 'Интерактивное обучение в реальном времени с переводом и белыми досками.',
    'showcase.multi_device.title': 'Синхронизация устройств',
    'showcase.multi_device.desc': 'Переключайтесь между Mac, iPad и iPhone, сохраняя прогресс в обучении.',
    'classroom.recording': 'Запись',
    'classroom.participants': 'Участники',
    'classroom.chat': 'Чат',
    'classroom.poll': 'Опрос',
    'classroom.translate': 'Перевод',
    'classroom.settings': 'Настройки',
    'classroom.mute': 'Выключить звук',
    'classroom.camera': 'Включить камеру',
    'classroom.screen': 'Демонстрация экрана',
    'classroom.leave': 'Выйти из класса',
    'classroom.topic': 'Тема дня',
    'classroom.subtitles': 'Субтитры в реальном времени',
    'classroom.bilingual': 'КИТ / АНГЛ',
    'classroom.students': 'Студенты',
    'classroom.active': 'Активно',
    'classroom.message_placeholder': 'Написать сообщение...',
    'classroom.poll_question': "Какой правильный пиньинь для '大家好'?",
    'vocab.study_modes': 'Режимы обучения',
    'vocab.search_placeholder': 'Поиск слов...',
    'vocab.launch_game': 'Запустить игру',
    'vocab.start_review': 'Начать повторение',
    'classroom.course_title': 'Китайский для начинающих (Ч. 1)',
    'dashboard.greeting_teacher': 'Здравствуйте, Ли Лаоши!',
    'dashboard.greeting_student': 'Привет, Анна!',
    'dashboard.overview': 'Вот обзор вашего расписания на сегодня.',
    'dashboard.view_all_action': 'Смотреть все',
    'dashboard.schedule_label': 'Задачи на сегодня',
    'homework.title': 'Разговорная практика',
    'homework.active_task': 'Активное задание',
    'homework.subtitle': 'Пожалуйста, четко прочитайте следующее предложение в микрофон.',
    'homework.due': 'Срок',
    'homework.today': 'Сегодня',
    'homework.pages': 'Страницы',
    'homework.tip': 'Совет: сосредоточьтесь на последовательности тонов и плавности.',
    'homework.recording': 'ЗАПИСЬ...',
    'homework.ready': 'Готовы к практике',
    'homework.latest': 'Последние записи (макс. 3)',
    'homework.score': 'Баллы',
    'homework.ai_eval': 'Оценка ИИ',
    'homework.total_score': 'БАЛЛЫ',
    'homework.excellent': 'Отлично!',
    'homework.great': 'Отличная работа!',
    'homework.keep_practicing': 'Продолжайте практиковаться!',
    'homework.eval_desc': 'У вас отличная беглость. Сосредоточьтесь на произношении конкретных иероглифов.',
    'homework.fluency': 'Беглость',
    'homework.tone': 'Точность тонов',
    'homework.pronunciation': 'Произношение',
    'homework.completeness': 'Полнота',
    'homework.grammar': 'Грамматика и исправления',
    'homework.tone_deviation': 'Отклонение тона',
    'homework.tone_desc': 'Обнаружено небольшое отклонение. Попробуйте подчеркнуть тон.',
    'homework.learning_tip': 'Совет по обучению',
    'homework.learning_desc': 'Запишите еще раз, сосредоточившись на дыхании.',
    'homework.model_answer': 'Вариант ответа',
    'homework.prev': 'Предыдущий вопрос',
    'homework.explain': 'Объяснить',
    'homework.save': 'Сохранить прогресс',
    'homework.next': 'Следующее задание',
    'homework.path_title': 'Мой путь обучения',
    'homework.path_desc': 'Выполняйте задания, соответствующие вашей школьной программе.',
    'homework.unit': 'Модуль',
    'homework.lesson': 'Урок',
    'homework.start_task': 'Начать задание',
    'homework.type.speaking': 'Разговорная практика',
    'homework.type.vocab': 'Упражнения на слова',
    'homework.type.reading': 'Понимание прочитанного',
    'homework.completed': 'Завершено',
    'homework.locked': 'Заблокировано',
    'homework.stats.title': 'Статистика',
    'homework.stats.mistakes': 'Ошибки',
    'homework.stats.favorites': 'Избранное',
    'homework.stats.records': 'История',
    'homework.stats.graph': 'Граф знаний',
    'homework.stats.syllabus': 'Учебный план',
    'homework.stats.mindmap': 'Интеллект-карта',
    'homework.stats.ranking': 'Рейтинги',
    'homework.stats.streak': 'Ударный режим',
    'homework.stats.points': 'Очки опыта',
    'vocab.study_now': 'Учить сейчас',
    'vocab.review': 'Повторить',
    'vocab.mastery': 'Освоение',
    'vocab.learning_title': 'Сессия обучения',
    'vocab.correct': 'Правильно!',
    'vocab.incorrect': 'Неправильно',
    'vocab.check': 'Проверить',
    'vocab.continue': 'Продолжить',
    'vocab.finish': 'Завершить сессию',
    'vocab.translate_to_ru': 'Перевести на русский',
    'vocab.translate_to_zh': 'Перевести на китайский',
    'vocab.pronounce': 'Произнесите слово',
    'vocab.phonetic_group': 'Фонетическая группа',

  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
